import ExcelJS from 'exceljs';
import { NextResponse } from 'next/server';
import { ApiError, withCompanyAuth } from '@/lib/api';
import { getDrawingTakeoffSnapshot } from '@/lib/reporting/drawing-takeoff';

export const runtime = 'nodejs'; export const dynamic = 'force-dynamic';
function id(request: Request) { const parts = new URL(request.url).pathname.split('/').filter(Boolean); const index = parts.indexOf('xlsx'); const value = decodeURIComponent(parts[index - 1] ?? ''); if (!value) throw ApiError.badRequest('TAKEOFF_ID_REQUIRED', 'sessionId is required.'); return value; }

export const GET = withCompanyAuth(['OWNER', 'ADMIN', 'SALES', 'VIEWER'], async (request, auth, company) => {
  const s = await getDrawingTakeoffSnapshot(company.companyId, id(request)); const ar = auth.user.locale.startsWith('ar'); const t = (a: string, e: string) => ar ? a : e; const book = new ExcelJS.Workbook(); book.creator = 'VOKA'; book.created = new Date(s.createdAt);
  const meta = book.addWorksheet(t('ملخص', 'Summary'), { views: [{ rightToLeft: ar }] }); meta.addRows([['Takeoff ID', s.id], ['Project', s.project], ['Source drawing', s.source.fileName], ['Source MIME type', s.source.mimeType], ['Source size bytes', s.source.sizeBytes], ['System / scope', s.systemScope], ['User intent', s.userIntent], ['Status', s.status], ['Version', s.version], ['Human Review Required', s.review.requiresHumanReview], ['Confirmed lines', s.review.confirmedLines], ['Needs-confirmation lines', s.review.needsConfirmationLines], ['Engineering approval', 'NO — human review state preserved'], ['Quotation ID', s.quotationId]]); meta.columns = [{ width: 28 }, { width: 72 }];
  const boq = book.addWorksheet('BOQ', { views: [{ rightToLeft: ar, state: 'frozen', ySplit: 1 }] }); boq.addRow(['Position', 'Detected item', 'Description', 'Quantity', 'Unit', 'Quantity provenance', 'Confidence', 'Human review state', 'Needs confirmation', 'Evidence / uncertainty', 'Mapped product/service', 'Catalog mapping', 'Governed unit price', 'Currency', 'Notes']); for (const line of s.lines) boq.addRow([line.position, line.detectedItem, line.description, line.quantity === null ? null : Number(line.quantity), line.unit, line.quantityProvenance, line.confidence === null ? null : Number(line.confidence), line.humanReviewState, line.needsConfirmation, line.evidence, line.mappedItem, line.catalogMapping, line.governedUnitPrice, line.currencyCode, line.notes]); boq.getRow(1).font = { bold: true }; boq.columns = [{ width: 10 }, { width: 28 }, { width: 40 }, { width: 16 }, { width: 14 }, { width: 24 }, { width: 14 }, { width: 20 }, { width: 20 }, { width: 40 }, { width: 25 }, { width: 24 }, { width: 22 }, { width: 12 }, { width: 30 }]; boq.getColumn(4).numFmt = '#,##0.000'; boq.getColumn(7).numFmt = '0.0000'; boq.getColumn(13).numFmt = '#,##0.000'; boq.autoFilter = { from: 'A1', to: 'O1' };
  const bytes = await book.xlsx.writeBuffer(); return new NextResponse(Buffer.from(bytes), { headers: { 'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'Content-Disposition': `attachment; filename="drawing-takeoff-${s.id}.xlsx"`, 'Cache-Control': 'private, no-store', 'X-Content-Type-Options': 'nosniff' } });
});
