import ExcelJS from 'exceljs';
import { NextResponse } from 'next/server';
import { ApiError, withCompanyAuth } from '@/lib/api';
import { getDrawingTakeoffSnapshot } from '@/lib/reporting/drawing-takeoff';
import { displayLabel } from '@/lib/i18n/display-labels';

export const runtime = 'nodejs'; export const dynamic = 'force-dynamic';
function id(request: Request) { const parts = new URL(request.url).pathname.split('/').filter(Boolean); const index = parts.indexOf('xlsx'); const value = decodeURIComponent(parts[index - 1] ?? ''); if (!value) throw ApiError.badRequest('TAKEOFF_ID_REQUIRED', 'sessionId is required.'); return value; }

export const GET = withCompanyAuth(['OWNER', 'ADMIN', 'SALES', 'VIEWER'], async (request, auth, company) => {
  const s = await getDrawingTakeoffSnapshot(company.companyId, id(request)); const ar = auth.user.locale.startsWith('ar'); const t = (a: string, e: string) => ar ? a : e; const locale = ar ? 'ar' : 'en'; const enumLabel = (value: string | null | undefined) => value == null ? null : displayLabel(value, locale); const book = new ExcelJS.Workbook(); book.creator = 'VOKA'; book.created = new Date(s.createdAt);
  const meta = book.addWorksheet(t('ملخص', 'Summary'), { views: [{ rightToLeft: ar }] }); meta.addRows([[t('رقم الحصر', 'Takeoff ID'), s.id], [t('المشروع', 'Project'), s.project], [t('ملف المصدر', 'Source drawing'), s.source.fileName], [t('نوع ملف المصدر', 'Source MIME type'), s.source.mimeType], [t('حجم المصدر (بايت)', 'Source size bytes'), s.source.sizeBytes], [t('النظام / النطاق', 'System / scope'), s.systemScope], [t('غرض المستخدم', 'User intent'), s.userIntent], [t('الحالة', 'Status'), enumLabel(s.status)], [t('الإصدار', 'Version'), s.version], [t('مراجعة بشرية مطلوبة', 'Human Review Required'), s.review.requiresHumanReview], [t('البنود المؤكدة', 'Confirmed lines'), s.review.confirmedLines], [t('البنود التي تحتاج تأكيدًا', 'Needs-confirmation lines'), s.review.needsConfirmationLines], [t('الاعتماد الهندسي', 'Engineering approval'), t('لا — حالة المراجعة البشرية محفوظة', 'NO — human review state preserved')], [t('رقم عرض السعر', 'Quotation ID'), s.quotationId]]); meta.columns = [{ width: 28 }, { width: 72 }];
  const boq = book.addWorksheet('BOQ', { views: [{ rightToLeft: ar, state: 'frozen', ySplit: 1 }] }); boq.addRow([t('الموضع', 'Position'), t('الصنف المكتشف', 'Detected item'), t('الوصف', 'Description'), t('الكمية', 'Quantity'), t('الوحدة', 'Unit'), t('مصدر الكمية', 'Quantity provenance'), t('الثقة', 'Confidence'), t('حالة المراجعة البشرية', 'Human review state'), t('يحتاج تأكيدًا', 'Needs confirmation'), t('الدليل / عدم اليقين', 'Evidence / uncertainty'), t('المنتج/الخدمة المرتبطة', 'Mapped product/service'), t('الربط بالكتالوج', 'Catalog mapping'), t('سعر الوحدة المحكوم', 'Governed unit price'), t('العملة', 'Currency'), t('ملاحظات', 'Notes')]); for (const line of s.lines) boq.addRow([line.position, line.detectedItem, line.description, line.quantity === null ? null : Number(line.quantity), line.unit, enumLabel(line.quantityProvenance), line.confidence === null ? null : Number(line.confidence), enumLabel(line.humanReviewState), line.needsConfirmation, line.evidence, line.mappedItem, line.catalogMapping, line.governedUnitPrice, line.currencyCode, line.notes]); boq.getRow(1).font = { bold: true }; boq.columns = [{ width: 10 }, { width: 28 }, { width: 40 }, { width: 16 }, { width: 14 }, { width: 24 }, { width: 14 }, { width: 20 }, { width: 20 }, { width: 40 }, { width: 25 }, { width: 24 }, { width: 22 }, { width: 12 }, { width: 30 }]; boq.getColumn(4).numFmt = '#,##0.000'; boq.getColumn(7).numFmt = '0.0000'; boq.getColumn(13).numFmt = '#,##0.000'; boq.autoFilter = { from: 'A1', to: 'O1' };
  const bytes = await book.xlsx.writeBuffer(); return new NextResponse(Buffer.from(bytes), { headers: { 'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'Content-Disposition': `attachment; filename="drawing-takeoff-${s.id}.xlsx"`, 'Cache-Control': 'private, no-store', 'X-Content-Type-Options': 'nosniff' } });
});
