"use client";
import Link from "next/link";import{useEffect,useState}from"react";import{DEFAULT_LOCALE,getDirection,type Locale}from"@/lib/i18n";
type K="product"|"drawing"|"commercial"|"how"|"insights"|"about"|"contact"|"privacy"|"terms";
const d:Record<K,{en:[string,string,string,string[]];ar:[string,string,string,string[]]}>= {
product:{en:["PRODUCT","Intent becomes controlled commercial execution.","Master data, commercial operations and reporting share one intelligence layer without giving AI financial authority.",["Customers, Products & Services","Quotations, Orders, Contracts, Invoices, Payments","Statements, Aging and Reporting"]],ar:["المنتج","يتحول القصد إلى تنفيذ تجاري منضبط.","تتشارك البيانات الأساسية والعمليات والتقارير طبقة ذكاء واحدة دون منح الذكاء سلطة مالية.",["العملاء والمنتجات والخدمات","العروض والأوامر والعقود والفواتير والمدفوعات","الكشوف وأعمار الديون والتقارير"]]},
drawing:{en:["TECHNICAL PREVIEW","From drawing to reviewable takeoff and quotation draft.","A bounded PDF-first CCTV / Low Voltage capability—not CAD or final engineering design. Uncertainty stays visible.",["Drawing + User Intent","Quantities with provenance","Catalog and approved pricing"]],ar:["معاينة تقنية","من المخطط إلى حصر قابل للمراجعة ومسودة عرض سعر.","قدرة محدودة تبدأ بملفات PDF لأنظمة CCTV والتيار الخفيف، وليست تصميمًا هندسيًا نهائيًا. يبقى عدم اليقين ظاهرًا.",["المخطط + طلب المستخدم","الكميات مع مصدرها","الكتالوج والتسعير المعتمد"]]},
commercial:{en:["ONE COMMERCIAL CHAIN","From quotation to collection—with source history intact.","Approved revisions stay immutable and every downstream document preserves its exact source.",["Quotation → Sales Order","Contract → Invoice","Payment → Statement"]],ar:["سلسلة تجارية واحدة","من عرض السعر إلى التحصيل مع بقاء تاريخ المصدر.","تبقى الإصدارات المعتمدة ثابتة ويحفظ كل مستند لاحق مصدره الدقيق.",["عرض السعر ← أمر البيع","العقد ← الفاتورة","الدفعة ← الكشف"]]},
how:{en:["HOW VOKA WORKS","AI understands. Rules calculate. Human approves.","Six governed stages keep intelligence separate from commercial authority.",["01 Input → 02 Interpret","03 Structure → 04 Rules","05 Review → 06 Execute"]],ar:["كيف يعمل VOKA","الذكاء يفهم. القواعد تحسب. الإنسان يعتمد.","ست مراحل محكومة تفصل الذكاء عن السلطة التجارية.",["01 الإدخال ← 02 التفسير","03 الهيكلة ← 04 القواعد","05 المراجعة ← 06 التنفيذ"]]},
insights:{en:["VOKA INSIGHTS","Knowledge for voice-first commercial operations.","Product notes on intent, document integrity, governed rules and bounded drawing intelligence.",["Voice-first operations","Revision and provenance","Drawing intelligence"]],ar:["معرفة VOKA","معرفة للعمليات التجارية التي تبدأ بالصوت.","ملاحظات حول القصد وسلامة المستندات والقواعد المحكومة وذكاء المخططات المحدود.",["عمليات تبدأ بالصوت","الإصدارات والمصدر","ذكاء المخططات"]]},
about:{en:["ABOUT VOKA","A Voice-First AI Sales OS built around commercial truth.","VOKA reduces fragmented administration without transferring financial or engineering authority to generative AI.",["AI understands","Rules calculate","Human approves"]],ar:["عن VOKA","نظام تشغيل مبيعات ذكي يبدأ بالصوت ويتمحور حول الحقيقة التجارية.","يقلل VOKA الإدارة المجزأة دون نقل السلطة المالية أو الهندسية إلى الذكاء التوليدي.",["الذكاء يفهم","القواعد تحسب","الإنسان يعتمد"]]},
contact:{en:["CONTACT","Start with a secure commercial conversation.","Public provider submission is not active. Use the authenticated workspace; live Email and WhatsApp remain externally pending.",["Secure workspace","Manual entry remains available","No fake delivery claims"]],ar:["تواصل معنا","ابدأ بمحادثة تجارية آمنة.","الإرسال العام عبر مزود غير مفعل. استخدم مساحة العمل الموثقة؛ ويبقى البريد وواتساب معلقًا خارجيًا.",["مساحة عمل آمنة","الإدخال اليدوي متاح","لا ادعاءات تسليم وهمية"]]},
privacy:{en:["PRIVACY","Company data remains inside governed tenant boundaries.","Authentication, authorization and server-owned company context protect product data. Final legal review remains required.",["Tenant isolation","Data minimization","Legal review pending"]],ar:["الخصوصية","تبقى بيانات الشركة داخل حدود المستأجر المحكومة.","تحمي المصادقة والتفويض وسياق الشركة الموثوق بيانات المنتج. تبقى المراجعة القانونية مطلوبة.",["عزل الشركات","تقليل البيانات","المراجعة القانونية معلقة"]]},
terms:{en:["TERMS","Controlled software, human decisions.","Users retain responsibility for approval, engineering review, contractual authority and lawful use.",["No autonomous authority","Traceable actions","Pre-production status"]],ar:["شروط الاستخدام","برنامج منضبط وقرارات بشرية.","يبقى المستخدم مسؤولًا عن الاعتماد والمراجعة الهندسية والسلطة التعاقدية والاستخدام القانوني.",["لا سلطة ذاتية","إجراءات قابلة للتتبع","حالة ما قبل الإنتاج"]]}};
const nav=[['Product','المنتج','/product'],['Drawing','المخططات','/drawing-intelligence'],['Operations','العمليات','/commercial-operations'],['How','كيف يعمل','/how-it-works'],['Insights','المعرفة','/insights'],['About','عن VOKA','/about'],['Contact','تواصل','/contact']]as const;
export function PublicSitePage({page}:{page:K}){const[l,setL]=useState<Locale>(DEFAULT_LOCALE);useEffect(()=>{const v=localStorage.getItem('voka-locale');if(v==='ar'||v==='en')setL(v)},[]);useEffect(()=>{localStorage.setItem('voka-locale',l);document.documentElement.lang=l;document.documentElement.dir=getDirection(l)},[l]);const c=d[page][l];return <main dir={getDirection(l)} className="min-h-screen bg-[#06101e] text-[#f7faff]"><header className="sticky top-0 z-40 border-b border-white/10 bg-[#06101e]/90"><div className="mx-auto flex min-h-[76px] max-w-[1180px] items-center justify-between px-4"><Link href="/" className="font-bold tracking-[.16em]">VOKA</Link><nav className="hidden gap-4 text-xs xl:flex">{nav.map(([en,ar,h])=><Link key={h} href={h}>{l==='ar'?ar:en}</Link>)}</nav><div className="flex gap-2"><button onClick={()=>setL('ar')} className="rounded-lg border border-white/10 px-2">AR</button><button onClick={()=>setL('en')} className="rounded-lg border border-white/10 px-2">EN</button><Link href="/login" className="rounded-lg border border-cyan-300/30 px-3 py-2">{l==='ar'?'دخول':'Sign in'}</Link></div></div></header><section className="mx-auto max-w-[1180px] px-4 py-24"><p className="text-xs font-bold tracking-[.15em] text-[#45dbff]">{c[0]}</p><h1 className="mt-5 max-w-4xl text-4xl font-bold sm:text-6xl">{c[1]}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-[#9eafc6]">{c[2]}</p><div className="mt-14 grid gap-5 md:grid-cols-3">{c[3].map((x,i)=><article key={x} className="min-h-52 rounded-3xl border border-white/10 bg-white/[.03] p-7"><span className="text-[#45dbff]">0{i+1}</span><h2 className="mt-5 text-xl font-bold">{x}</h2></article>)}</div></section><footer className="border-t border-white/10 py-10"><div className="mx-auto flex max-w-[1180px] justify-between px-4 text-sm text-[#9eafc6]"><span>© 2026 VOKA</span><span className="flex gap-4"><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link></span></div></footer></main>}
