"use client";

import { useState, type ReactNode } from "react";
import type { SystemConfigurationGraph } from "@/src/application/conversation-runtime";
import { AssistantIcon } from "./AssistantIcon";

export function SolutionWorkspace({ graph, isArabic, onOpenDraft, draftLoading, error }: { graph: SystemConfigurationGraph; isArabic: boolean; onOpenDraft: () => void; draftLoading: boolean; error?: string | null }) {
  const [mobileOpen, setMobileOpen] = useState(false);
  const t = (ar: string, en: string) => isArabic ? ar : en;
  if (!graph.system) return null;
  const body = <div className="space-y-4" data-testid="solution-workspace-content">
    <section><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-sky-300/70">{t("الحل", "Solution")}</p><h2 className="mt-1 text-base font-semibold text-slate-100">{isArabic ? graph.system.nameAr : graph.system.nameEn}</h2>{graph.requirements.length ? <div className="mt-3 grid gap-1.5">{graph.requirements.map((item) => <div key={item.key} className="flex items-start justify-between gap-3 rounded-xl bg-white/[0.025] px-3 py-2 text-xs"><span className="text-slate-500">{isArabic ? item.labelAr : item.labelEn}</span><span className="text-end font-medium text-slate-200">{String(item.value)}</span></div>)}</div> : null}</section>
    {graph.candidateProducts.length ? <Section title={t("خيارات المنتجات", "Product options")}><div className="space-y-2">{graph.candidateProducts.map((item) => <div key={item.id} className="rounded-xl border border-white/[0.06] bg-white/[0.025] p-2.5"><p className="text-xs font-medium text-slate-200">{(isArabic ? item.nameAr : item.nameEn) || item.name}</p><p className="mt-1 text-[10px] text-slate-500">{item.source === "VERIFIED_CATALOG" ? t("من كتالوج الشركة", "Company catalog") : t("اقتراح بحثي — يحتاج اعتماد", "Research suggestion — review required")}</p></div>)}</div></Section> : null}
    {graph.engineeringBom.length ? <Section title={t("قائمة التنفيذ والتوريد", "Engineering / procurement BOM")}><Bom lines={graph.engineeringBom} isArabic={isArabic} showRationale /></Section> : null}
    {graph.salesBom.length ? <Section title={t("بنود عرض السعر", "Sales BOM")}><Bom lines={graph.salesBom} isArabic={isArabic} /></Section> : null}
    {graph.unresolvedDecisions.length ? <Section title={t("قرارات مؤثرة ما زالت مفتوحة", "Meaningful open decisions")}><ul className="space-y-1.5 text-xs text-amber-100/80">{graph.unresolvedDecisions.map((item) => <li key={item.key} className="rounded-lg bg-amber-300/[0.045] px-2.5 py-2">{isArabic ? item.labelAr : item.labelEn}</li>)}</ul></Section> : null}
    <section className="rounded-2xl border border-emerald-300/15 bg-emerald-300/[0.045] p-3.5" data-testid="draft-readiness"><div className="flex items-center gap-2 text-sm font-semibold text-emerald-100"><AssistantIcon name="sparkles" className="h-4 w-4" />{t("المسودة جاهزة للفتح", "Draft ready to open")}</div>{graph.readiness.pendingBeforeFinalIssue.length ? <p className="mt-2 text-[11px] leading-5 text-slate-400">{t("يمكن استكمالها قبل الإصدار النهائي: ", "Can be completed before final issue: ")}{graph.readiness.pendingBeforeFinalIssue.join(isArabic ? "، " : ", ")}</p> : null}{error ? <p role="alert" className="mt-2 text-xs text-amber-200">{error}</p> : null}<button type="button" aria-label={t("جهّز العرض", "Prepare quotation")} onClick={onOpenDraft} disabled={draftLoading} className="mt-3 w-full rounded-xl bg-emerald-300 px-3 py-2.5 text-xs font-bold text-slate-950 outline-none transition hover:bg-emerald-200 focus-visible:ring-2 focus-visible:ring-emerald-300 disabled:cursor-wait disabled:opacity-60">{draftLoading ? t("جارٍ فتح المسودة…", "Opening draft…") : t("افتح المسودة الآن", "Open Draft now")}</button></section>
  </div>;
  return <><button type="button" onClick={() => setMobileOpen((value) => !value)} className="flex w-full items-center justify-between rounded-2xl border border-sky-300/15 bg-slate-950/70 px-4 py-3 text-sm font-semibold text-slate-100 xl:hidden" aria-expanded={mobileOpen}><span>{t("مساحة الحل", "Solution Workspace")}</span><AssistantIcon name="chevron" className={`h-4 w-4 transition ${mobileOpen ? "rotate-90" : ""}`} /></button>{mobileOpen ? <aside className="max-h-[65vh] overflow-y-auto rounded-2xl border border-white/[0.07] bg-slate-950/80 p-4 xl:hidden" aria-label={t("مساحة الحل", "Solution Workspace")}>{body}</aside> : null}<aside data-testid="solution-workspace" className="hidden min-w-0 self-start overflow-hidden rounded-3xl border border-white/[0.075] bg-slate-950/65 shadow-[0_24px_80px_-48px_rgba(56,189,248,.35)] backdrop-blur-xl xl:sticky xl:top-4 xl:block xl:h-[calc(100vh-8rem)]" aria-label={t("مساحة الحل", "Solution Workspace")}><div className="border-b border-white/[0.06] px-4 py-3"><p className="text-sm font-semibold text-slate-100">{t("مساحة الحل", "Solution Workspace")}</p><p className="mt-0.5 text-[10px] text-slate-500">{t("تتحدث أنت، وفوكا يبني الحل", "You talk; VOKA builds the solution")}</p></div><div className="h-[calc(100%-3.9rem)] overflow-y-auto p-4 [scrollbar-width:thin]">{body}</div></aside></>;
}

function Section({ title, children }: { title: string; children: ReactNode }) { return <section><h3 className="mb-2 text-xs font-semibold text-slate-300">{title}</h3>{children}</section>; }
function Bom({ lines, isArabic, showRationale = false }: { lines: SystemConfigurationGraph["salesBom"]; isArabic: boolean; showRationale?: boolean }) { return <div className="space-y-1.5">{lines.map((item) => <div key={item.id} className="rounded-xl border border-white/[0.055] bg-white/[0.02] p-2.5"><div className="flex items-start justify-between gap-2"><p className="text-xs font-medium leading-5 text-slate-200">{isArabic ? item.itemNameAr : item.itemNameEn}</p><span className="shrink-0 text-[10px] text-slate-400">{item.quantityState === "PENDING" ? (isArabic ? "الكمية لاحقًا" : "Qty pending") : `${item.quantity} ${item.unitName ?? ""}`}</span></div>{showRationale && item.description ? <p className="mt-1 line-clamp-2 text-[10px] leading-4 text-slate-500">{item.description}</p> : null}<p className="mt-1 text-[10px] text-slate-500">{item.priceState === "PENDING" ? (isArabic ? "السعر لاحقًا" : "Price pending") : item.unitPrice}</p></div>)}</div>; }
