"use client";
import { useMemo, useState } from "react";
import { Input, Modal } from "@/components/ui";
import { CustomerForm, customerFormPayload, emptyCustomerForm } from "@/features/customers/components/CustomerForm";

export type CommercialCustomerOption = { id: string; name: string; nameAr?: string | null; nameEn?: string | null };
export function CustomerPicker({ customers, value, isArabic, onChange, onCreated }: { customers: CommercialCustomerOption[]; value: string; isArabic: boolean; onChange: (id: string) => void; onCreated: (customer: CommercialCustomerOption) => void }) {
  const t = (ar: string, en: string) => isArabic ? ar : en; const selected = customers.find((customer) => customer.id === value);
  const selectedName = selected ? (isArabic ? selected.nameAr || selected.name : selected.nameEn || selected.name) : null;
  // The canonical selection may arrive after mount (AI handoff / async options).
  // Search text is only local input; it must not hide or retain a stale selection.
  const [query, setQuery] = useState(""), [open, setOpen] = useState(false), [modal, setModal] = useState(false), [error, setError] = useState(""), [creating, setCreating] = useState(false);
  const matches = useMemo(() => customers.filter((customer) => `${customer.name} ${customer.nameAr ?? ""} ${customer.nameEn ?? ""}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())).slice(0, 8), [customers, query]);
  const choose = (customer: CommercialCustomerOption) => { onChange(customer.id); setQuery(""); setOpen(false); };
  async function create(payload: Record<string, unknown>) { setCreating(true); setError(""); try { const response = await fetch("/api/customers", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json().catch(() => null); if (!response.ok || !body?.data?.customer) throw new Error(body?.error?.message ?? t("تعذر إنشاء العميل", "Unable to create customer")); onCreated(body.data.customer); choose(body.data.customer); setModal(false); } catch (caught) { setError(caught instanceof Error ? caught.message : "Create failed"); } finally { setCreating(false); } }
  const canCreate = query.trim().length >= 2 && !customers.some((customer) => [customer.name, customer.nameAr, customer.nameEn].some((name) => name?.trim().toLocaleLowerCase() === query.trim().toLocaleLowerCase()));
  return <div className="relative"><Input aria-label={t("بحث العميل", "Customer search")} value={selectedName ?? query} onFocus={() => setOpen(true)} onChange={(event) => { setQuery(event.target.value); onChange(""); setOpen(true); }} placeholder={t("ابحث أو أنشئ عميلًا", "Search or create a customer")} />{open ? <div className="absolute z-30 mt-2 max-h-72 w-full overflow-auto rounded-xl border border-white/10 bg-slate-950 p-2 shadow-2xl">{matches.map((customer) => <button type="button" key={customer.id} onClick={() => choose(customer)} className="block w-full rounded-lg px-3 py-2 text-start text-sm hover:bg-white/5">{isArabic ? customer.nameAr || customer.name : customer.nameEn || customer.name}</button>)}{canCreate ? <div className="mt-1 border-t border-white/10 pt-1"><button type="button" disabled={creating} onClick={() => void create({ [isArabic ? "nameAr" : "nameEn"]: query.trim(), type: "COMPANY", status: "LEAD" })} className="block w-full rounded-lg px-3 py-2 text-start text-sm text-sky-300 hover:bg-sky-400/5">{t(`إنشاء "${query.trim()}"`, `Create "${query.trim()}"`)}</button><button type="button" onClick={() => { setOpen(false); setModal(true); }} className="block w-full rounded-lg px-3 py-2 text-start text-sm text-violet-300 hover:bg-violet-400/5">{t("إنشاء وتعديل...", "Create & Edit…")}</button></div> : null}{!matches.length && !canCreate ? <p className="px-3 py-2 text-sm text-slate-500">{t("لا توجد نتائج", "No matches")}</p> : null}</div> : null}{error ? <p className="mt-2 text-sm text-red-300">{error}</p> : null}<Modal open={modal} onClose={() => setModal(false)} title={t("إنشاء عميل دون مغادرة المستند", "Create customer without leaving the document")} description={t("أكمل بيانات العميل ثم تابع المستند من نفس السياق.", "Complete customer details and continue the document in place.")}><CustomerForm isArabic={isArabic} initialValue={{ ...emptyCustomerForm, ...(isArabic ? { nameAr: query.trim() } : { nameEn: query.trim() }) }} submitLabel={t("إنشاء ومتابعة", "Create and continue")} onSubmit={async (form) => create(customerFormPayload(form))} /></Modal></div>;
}
