"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { Button, Card, Input, SectionHeader } from "../../../../components/ui";
import { useLanguage } from "../../../../components/i18n/LanguageProvider";

type Customer={id:string;name:string};
type Item={id:string;name:string;code:string;type:string;salePrice:number;taxRateId?:string|null};
type Line={catalogItemId:string;type:string;itemCode:string;itemName:string;unitName:string;quantity:number;unitPrice:number;taxRateId?:string|null};

export default function NewQuotationPage(){
 const {isArabic}=useLanguage();const router=useRouter();const [customers,setCustomers]=useState<Customer[]>([]);const [items,setItems]=useState<Item[]>([]);const [customerId,setCustomerId]=useState("");const [number,setNumber]=useState("QT-"+Date.now().toString().slice(-6));const [lines,setLines]=useState<Line[]>([]);const [notes,setNotes]=useState("");const [terms,setTerms]=useState("");const [discountType,setDiscountType]=useState<""|"FIXED"|"PERCENTAGE">("");const [discountValue,setDiscountValue]=useState(0);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [dirty,setDirty]=useState(false);
 useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue=""}};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn)},[dirty]);
 useEffect(()=>{(async()=>{try{setLoading(true);const me=await fetch("/api/auth/me");if(!me.ok)throw new Error(isArabic?"يلزم تسجيل الدخول":"Please sign in");const auth=(await me.json()).data;const companyId=auth.activeCompanyId;if(!companyId)throw new Error(isArabic?"لا توجد شركة نشطة":"No active company");const [cr,ir]=await Promise.all([fetch("/api/customers?companyId="+companyId+"&pageSize=100"),fetch("/api/catalog/items?pageSize=100&isActive=true")]);if(!cr.ok||!ir.ok)throw new Error(isArabic?"تعذر تحميل بيانات النموذج":"Unable to load form data");const cj=await cr.json(),ij=await ir.json();setCustomers(cj.data.customers);setItems(ij.data); }catch(e){setError(e instanceof Error?e.message:"Load failed")}finally{setLoading(false)}})()},[isArabic]);
 const selectedCustomer=customers.find(c=>c.id===customerId);const subtotal=useMemo(()=>lines.reduce((sum,line)=>sum+line.quantity*line.unitPrice,0),[lines]);const discountAmount=discountType==="PERCENTAGE"?subtotal*Math.min(100,discountValue)/100:discountType==="FIXED"?Math.min(subtotal,discountValue):0;const total=subtotal-discountAmount;
 function addItem(id:string){setDirty(true);if(id==="__custom"){setLines(value=>[...value,{catalogItemId:"",type:"CUSTOM",itemCode:"",itemName:isArabic?"بند مخصص":"Custom line",unitName:"PCS",quantity:1,unitPrice:0}]);return}const item=items.find(value=>value.id===id);if(!item)return;setLines(value=>[...value,{catalogItemId:item.id,type:item.type,itemCode:item.code,itemName:item.name,unitName:"PCS",quantity:1,unitPrice:item.salePrice,taxRateId:item.taxRateId}])}
 function change(index:number,key:"quantity"|"unitPrice"|"itemName"|"unitName",value:number|string){setDirty(true);setLines(current=>current.map((line,i)=>i===index?{...line,[key]:value}:line))}
 function cancel(){if(!dirty||window.confirm(isArabic?"هل تريد إلغاء العرض؟ ستفقد التغييرات غير المحفوظة.":"Cancel this quotation? Unsaved changes will be lost."))router.push("/dashboard/quotations")}
 async function submit(event:React.FormEvent){event.preventDefault();if(!selectedCustomer||lines.length===0)return;try{setSaving(true);setError("");const response=await fetch("/api/quotations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({customerId,quotationNumber:number,currencyCode:"KWD",customer:{name:selectedCustomer.name},lines:lines.map((line,index)=>({...line,catalogItemId:line.catalogItemId||null,position:index+1})),notes,termsAndConditions:terms,discount:discountType?{type:discountType,value:discountValue}:null})});const json=await response.json();if(!response.ok)throw new Error(json?.error?.message??"Create failed");setDirty(false);router.push("/dashboard/quotations/"+json.data.id)}catch(e){setError(e instanceof Error?e.message:"Create failed")}finally{setSaving(false)}}
 return <section className="space-y-6" dir={isArabic?"rtl":"ltr"}><button type="button" onClick={cancel} className="text-sm text-sky-300">{isArabic?"العودة للعروض":"Back to quotations"}</button><SectionHeader eyebrow={isArabic?"عرض جديد":"New quotation"} title={isArabic?"إنشاء عرض سعر":"Create quotation"} description={isArabic?"اختر العميل وأضف المنتجات أو الخدمات.":"Select a customer and add products or services."}/>
 {loading?<Card><div className="h-40 animate-pulse rounded-2xl bg-white/5"/></Card>:<form onSubmit={submit} className="space-y-6">
 {error&&<Card className="border-red-400/20 bg-red-400/5"><p className="text-red-300">{error}</p></Card>}
 <Card><div className="grid gap-4 md:grid-cols-2"><label className="space-y-2"><span className="text-sm text-slate-400">{isArabic?"العميل":"Customer"}</span><select required value={customerId} onChange={e=>{setCustomerId(e.target.value);setDirty(true)}} className="min-h-11 w-full rounded-xl border border-white/10 bg-slate-950 px-4"><option value="">{isArabic?"اختر العميل":"Select customer"}</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="space-y-2"><span className="text-sm text-slate-400">{isArabic?"رقم العرض":"Quotation number"}</span><Input required value={number} onChange={e=>{setNumber(e.target.value);setDirty(true)}}/></label></div></Card>
 <Card><h3 className="font-semibold">{isArabic?"بنود العرض":"Quotation lines"}</h3><div className="mt-3 space-y-1"><div className="grid gap-3 px-4 text-xs font-medium uppercase tracking-wider text-slate-500 md:grid-cols-[1fr_100px_120px_140px_140px_auto]"><label className="space-y-1"><span>{isArabic?"المنتج أو الخدمة":"Product or service"}</span><select defaultValue="" onChange={e=>{addItem(e.target.value);e.target.value=""}} className="min-h-11 w-full rounded-xl border border-white/10 bg-slate-950 px-4 text-sm font-normal normal-case tracking-normal text-white"><option value="">{isArabic?"إضافة منتج أو خدمة":"Add product or service"}</option><option value="__custom">{isArabic?"+ بند مخصص":"+ Custom line"}</option>{items.map(i=><option key={i.id} value={i.id}>{i.code} - {i.name}</option>)}</select></label><span className="hidden md:block">{isArabic?"الوحدة":"Unit"}</span><span className="hidden md:block">{isArabic?"الكمية":"Quantity"}</span><span className="hidden md:block">{isArabic?"سعر الوحدة":"Unit price"}</span><span className="hidden md:block">{isArabic?"الإجمالي":"Total"}</span><span className="hidden md:block">{isArabic?"إجراء":"Action"}</span></div>{lines.length===0&&<p className="py-3 text-center text-sm text-slate-500">{isArabic?"أضف بندًا واحدًا على الأقل":"Add at least one line"}</p>}{lines.map((line,index)=><div key={index} className="grid gap-3 rounded-2xl border border-white/5 p-4 md:grid-cols-[1fr_100px_120px_140px_140px_auto]"><div><Input value={line.itemName} onChange={e=>change(index,"itemName",e.target.value)}/><p className="mt-1 text-xs text-slate-500">{line.itemCode||line.type}</p></div><Input value={line.unitName} onChange={e=>change(index,"unitName",e.target.value)} placeholder={isArabic?"الوحدة":"Unit"}/><Input type="number" min="0.001" step="0.001" value={line.quantity} onChange={e=>change(index,"quantity",Number(e.target.value))}/><Input type="number" min="0" step="0.001" value={line.unitPrice} onChange={e=>change(index,"unitPrice",Number(e.target.value))}/><div className="flex min-h-11 items-center rounded-xl border border-white/10 bg-white/[0.03] px-3 font-semibold text-emerald-300">{(line.quantity*line.unitPrice).toFixed(3)}</div><Button variant="danger" size="sm" onClick={()=>{setLines(v=>v.filter((_,i)=>i!==index));setDirty(true)}}>{isArabic?"حذف":"Remove"}</Button></div>)}</div></Card>
 <Card><div className="mb-5 grid gap-4 border-b border-white/10 pb-5 md:grid-cols-2"><label className="space-y-2"><span className="text-sm text-slate-400">{isArabic?"نوع الخصم":"Discount type"}</span><select value={discountType} onChange={e=>{setDiscountType(e.target.value as ""|"FIXED"|"PERCENTAGE");setDirty(true)}} className="min-h-11 w-full rounded-xl border border-white/10 bg-slate-950 px-4"><option value="">{isArabic?"بدون خصم":"No discount"}</option><option value="PERCENTAGE">{isArabic?"نسبة مئوية":"Percentage"}</option><option value="FIXED">{isArabic?"مبلغ ثابت":"Fixed amount"}</option></select></label><label className="space-y-2"><span className="text-sm text-slate-400">{isArabic?"قيمة الخصم":"Discount value"}</span><Input type="number" min="0" max={discountType==="PERCENTAGE"?100:undefined} step="0.001" disabled={!discountType} value={discountValue} onChange={e=>{setDiscountValue(Number(e.target.value));setDirty(true)}}/></label></div><div className="grid gap-4 md:grid-cols-2"><label className="space-y-2"><span className="text-sm text-slate-400">{isArabic?"ملاحظات":"Notes"}</span><textarea value={notes} onChange={e=>{setNotes(e.target.value);setDirty(true)}} className="min-h-24 w-full rounded-xl border border-white/10 bg-slate-950 p-4"/></label><label className="space-y-2"><span className="text-sm text-slate-400">{isArabic?"الشروط والأحكام":"Terms and conditions"}</span><textarea value={terms} onChange={e=>{setTerms(e.target.value);setDirty(true)}} className="min-h-24 w-full rounded-xl border border-white/10 bg-slate-950 p-4"/></label></div><div className="mt-5 flex items-center justify-between border-t border-white/10 pt-5"><div><p className="text-sm text-slate-500">{isArabic?"الإجمالي المتوقع":"Estimated total"}</p><p className="mt-1 text-2xl font-semibold text-emerald-300">{total.toFixed(3)} KWD</p></div><div className="flex gap-3"><Button variant="secondary" onClick={cancel}>{isArabic?"إلغاء":"Cancel"}</Button><Button type="submit" disabled={saving||!customerId||lines.length===0}>{saving?(isArabic?"جارٍ الحفظ...":"Saving..."):(isArabic?"إنشاء العرض":"Create quotation")}</Button></div></div></Card>
 </form>}</section>
}
