"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import { Badge, Button, Card, SectionHeader } from "../../../../components/ui";
import { useLanguage } from "../../../../components/i18n/LanguageProvider";

type Line={id?:string;position:number;itemName:string;quantity:number;unitPrice:number;unitName?:string|null;taxAmount:number;totalAmount:number};
type Quote={id:string;quotationNumber:string;status:string;issueDate:string;expiryDate:string|null;currencyCode:string;customer:{name:string;email?:string|null;phone?:string|null};lines:Line[];totals:{subtotal:number;discountAmount:number;taxAmount:number;totalAmount:number};notes?:string|null;termsAndConditions?:string|null};
const ar:Record<string,string>={DRAFT:"مسودة",SENT:"مرسل",APPROVED:"معتمد",REJECTED:"مرفوض",EXPIRED:"منتهي",CANCELLED:"ملغي"};

export default function QuotationDetailsPage(){
 const {isArabic}=useLanguage();const params=useParams<{quotationId:string}>();const [quote,setQuote]=useState<Quote|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [acting,setActing]=useState("");
 const load=useCallback(async()=>{try{setLoading(true);setError("");const r=await fetch("/api/quotations/"+encodeURIComponent(params.quotationId));if(r.status===401)throw new Error(isArabic?"يلزم تسجيل الدخول أولًا":"Please sign in first");if(r.status===404)throw new Error(isArabic?"عرض السعر غير موجود":"Quotation not found");if(!r.ok)throw new Error(isArabic?"تعذر تحميل العرض":"Unable to load quotation");const j=await r.json();setQuote(j.data)}catch(e){setError(e instanceof Error?e.message:"Unknown error")}finally{setLoading(false)}},[isArabic,params.quotationId]);useEffect(()=>{load()},[load]);
 async function action(name:string){if(!quote||!window.confirm(isArabic?"هل تريد تنفيذ هذا الإجراء؟":"Do you want to continue?"))return;try{setActing(name);setError("");const r=await fetch("/api/quotations/"+quote.id+"/"+name,{method:"POST"});if(!r.ok){const j=await r.json().catch(()=>null);throw new Error(j?.error?.message??"Action failed")}await load()}catch(e){setError(e instanceof Error?e.message:"Action failed")}finally{setActing("")}}
 const money=(n:number)=>new Intl.NumberFormat(isArabic?"ar-KW":"en-US",{style:"currency",currency:quote?.currencyCode??"KWD"}).format(n);
 if(loading)return <Card><div className="h-40 animate-pulse rounded-2xl bg-white/5"/></Card>;
 if(error&&!quote)return <Card className="border-red-400/20 bg-red-400/5"><p className="text-red-300">{error}</p><Link href="/dashboard/quotations" className="mt-4 inline-block text-sky-300">{isArabic?"العودة للعروض":"Back to quotations"}</Link></Card>;
 if(!quote)return null;
 const actions=quote.status==="DRAFT"?["send","cancel"]:quote.status==="SENT"?["approve","reject","cancel"]:quote.status==="APPROVED"?["cancel"]:[];
 return <section className="space-y-6" dir={isArabic?"rtl":"ltr"}><Link href="/dashboard/quotations" className="text-sm text-sky-300">{isArabic?"العودة لعروض الأسعار":"Back to quotations"}</Link>
 <SectionHeader eyebrow={isArabic?"تفاصيل العرض":"Quotation details"} title={quote.quotationNumber} description={quote.customer.name} actions={<div className="flex gap-2"><a href={`/api/quotations/${encodeURIComponent(quote.id)}/pdf?locale=${isArabic?"ar":"en"}`}><Button size="sm" variant="secondary">{isArabic?"تنزيل PDF":"Download PDF"}</Button></a>{quote.status==="DRAFT"&&<Link href={"/dashboard/quotations/"+quote.id+"/edit"}><Button size="sm" variant="secondary">{isArabic?"تعديل":"Edit"}</Button></Link>}<Badge>{isArabic?(ar[quote.status]??quote.status):quote.status}</Badge>{actions.map(name=><Button key={name} size="sm" variant={name==="approve"?"success":name==="reject"||name==="cancel"?"danger":"primary"} disabled={!!acting} onClick={()=>action(name)}>{acting===name?"...":name}</Button>)}</div>}/>
 {error&&<Card className="border-red-400/20 bg-red-400/5"><p className="text-red-300">{error}</p></Card>}
 <div className="grid gap-4 md:grid-cols-3"><Card><p className="text-sm text-slate-500">{isArabic?"العميل":"Customer"}</p><p className="mt-3 font-semibold">{quote.customer.name}</p><p className="mt-1 text-sm text-slate-400">{quote.customer.email||quote.customer.phone||"—"}</p></Card><Card><p className="text-sm text-slate-500">{isArabic?"تاريخ الإصدار":"Issue date"}</p><p className="mt-3 font-semibold">{new Date(quote.issueDate).toLocaleDateString(isArabic?"ar-KW":"en-GB")}</p></Card><Card><p className="text-sm text-slate-500">{isArabic?"الإجمالي":"Total"}</p><p className="mt-3 text-2xl font-semibold text-emerald-300">{money(quote.totals.totalAmount)}</p></Card></div>
 <Card padding="none"><div className="border-b border-white/10 px-6 py-4 font-semibold">{isArabic?"بنود العرض":"Quotation lines"}</div><div className="divide-y divide-white/5">{quote.lines.map(line=><div key={line.id??line.position} className="grid grid-cols-[1fr_auto] gap-4 px-6 py-4"><div><p className="font-medium">{line.itemName}</p><p className="mt-1 text-sm text-slate-500">{line.quantity} {line.unitName||""} × {money(line.unitPrice)}</p></div><p className="font-semibold">{money(line.totalAmount)}</p></div>)}</div></Card>
 <Card><div className="ms-auto max-w-md space-y-3"><div className="flex justify-between"><span className="text-slate-500">{isArabic?"المجموع الفرعي":"Subtotal"}</span><span>{money(quote.totals.subtotal)}</span></div>{quote.totals.discountAmount>0&&<div className="flex justify-between text-amber-300"><span>{isArabic?"الخصم":"Discount"}</span><span>- {money(quote.totals.discountAmount)}</span></div>}<div className="flex justify-between"><span className="text-slate-500">{isArabic?"الضريبة":"Tax"}</span><span>{money(quote.totals.taxAmount)}</span></div><div className="flex justify-between border-t border-white/10 pt-3 text-lg font-semibold"><span>{isArabic?"الإجمالي":"Total"}</span><span className="text-emerald-300">{money(quote.totals.totalAmount)}</span></div></div></Card>
 {quote.notes&&<Card><p className="text-sm text-slate-500">{isArabic?"ملاحظات":"Notes"}</p><p className="mt-3 whitespace-pre-wrap">{quote.notes}</p></Card>}{quote.termsAndConditions&&<Card><p className="text-sm text-slate-500">{isArabic?"الشروط والأحكام":"Terms and conditions"}</p><p className="mt-3 whitespace-pre-wrap">{quote.termsAndConditions}</p></Card>}</section>
}
