import path from "node:path";
import PDFDocument from "pdfkit";
import { NextResponse } from "next/server";
import { ApiError, withCompanyAuth } from "@/lib/api";
import { prisma } from "@/lib/prisma";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
function id(request: Request) { const p = new URL(request.url).pathname.split("/").filter(Boolean); const i = p.indexOf("pdf"); if (i < 1) throw ApiError.badRequest("INVOICE_ID_REQUIRED", "invoiceId is required."); return decodeURIComponent(p[i - 1]); }
function language(request: Request, fallback: string): "ar"|"en" { const v = new URL(request.url).searchParams.get("locale"); if (v && v !== "ar" && v !== "en") throw ApiError.badRequest("DOCUMENT_LOCALE_INVALID", "locale must be ar or en."); return v === "ar" || (!v && fallback.startsWith("ar")) ? "ar" : "en"; }
async function pdf(row: any, locale: "ar"|"en") { const doc = new PDFDocument({ size:"A4", margin:42, info:{ Title:row.number, Author:row.company.name } }); const chunks:Buffer[]=[]; doc.on("data", x=>chunks.push(Buffer.from(x))); const finished=new Promise<Buffer>((resolve,reject)=>{doc.on("end",()=>resolve(Buffer.concat(chunks)));doc.on("error",reject)}); doc.registerFont("VOKA",path.join(process.cwd(),"assets","fonts","Cairo-Variable.ttf")).font("VOKA"); const ar=locale==="ar", t=(a:string,e:string)=>ar?a:e, o={align:ar?"right" as const:"left" as const};
 doc.fillColor("#0f172a").fontSize(24).text(row.company.name,o).fontSize(11).fillColor("#64748b").text(t("فاتورة","INVOICE"),o).fontSize(20).fillColor("#0369a1").text(row.number,o).moveDown().fontSize(10).fillColor("#334155").text(`${t("العميل","Customer")}: ${ar?row.customerNameAr??row.customerName:row.customerNameEn??row.customerName}`,o).text(`${t("تاريخ الفاتورة","Invoice date")}: ${row.invoiceDate.toISOString().slice(0,10)}`,o).text(`${t("الاستحقاق","Due")}: ${row.dueDate?.toISOString().slice(0,10)??"—"}`,o).text(`${t("الحالة","Status")}: ${row.status} / ${row.settlementStatus}`,o).moveDown();
 row.lines.forEach((line:any)=>{if(doc.y>680)doc.addPage();doc.fontSize(9).fillColor("#0f172a").text(`${line.position}. ${ar?line.itemNameAr??line.itemName:line.itemNameEn??line.itemName}`,{...o,continued:false}).fontSize(8).fillColor("#64748b").text(`${Number(line.quantity).toFixed(3)} × ${Number(line.unitPrice).toFixed(3)} = ${Number(line.totalAmount).toFixed(3)} ${row.currencyCode}`,o).moveDown(.4)});
 const m=(v:any)=>`${Number(v).toFixed(3)} ${row.currencyCode}`; doc.moveDown().fontSize(10).fillColor("#334155").text(`${t("المجموع الفرعي","Subtotal")}: ${m(row.subtotal)}`,o).text(`${t("الخصم","Discount")}: ${m(row.discountAmount)}`,o).text(`${t("الضريبة","Tax")}: ${m(row.taxAmount)}`,o).fontSize(14).fillColor("#0369a1").text(`${t("الإجمالي","Total")}: ${m(row.totalAmount)}`,o).fontSize(10).fillColor("#334155").text(`${t("المدفوع","Paid")}: ${m(row.paidAmount)}`,o).text(`${t("المتبقي","Outstanding")}: ${m(row.outstandingAmount)}`,o); if(row.notes)doc.moveDown().text(`${t("ملاحظات","Notes")}: ${row.notes}`,o);doc.end();return finished; }
export const GET=withCompanyAuth(["OWNER","ADMIN","SALES","VIEWER"],async(request,auth,company)=>{const row=await prisma.invoice.findFirst({where:{id:id(request),companyId:company.companyId},include:{company:true,lines:{orderBy:{position:"asc"}}}});if(!row)throw ApiError.notFound("INVOICE_NOT_FOUND","Invoice not found.");const bytes=await pdf(row,language(request,auth.user.locale));return new NextResponse(bytes,{headers:{"Content-Type":"application/pdf","Content-Disposition":`attachment; filename="invoice-${row.number.replace(/[^A-Za-z0-9._-]/g,"-")}.pdf"`,"Cache-Control":"private, no-store","X-Content-Type-Options":"nosniff"}})});
