export const MAX_DRAWING_BYTES = 15 * 1024 * 1024;
export const MAX_TAKEOFF_LINES = 200;
export type TakeoffProvenance = "DRAWING_COUNTED" | "DRAWING_MEASURED" | "CALCULATED" | "USER_PROVIDED" | "AI_INTERPRETED" | "CATALOG_MAPPED" | "NEEDS_CONFIRMATION";
export type TakeoffLineInput = { itemName: unknown; description?: unknown; quantity?: unknown; unitName?: unknown; provenance?: unknown; evidence?: unknown; confidence?: unknown; isConfirmed?: unknown };
export class DrawingTakeoffPolicyError extends Error { constructor(public readonly code: string, message: string) { super(message); } }
const provenance = new Set<TakeoffProvenance>(["DRAWING_COUNTED", "DRAWING_MEASURED", "CALCULATED", "USER_PROVIDED", "AI_INTERPRETED", "CATALOG_MAPPED", "NEEDS_CONFIRMATION"]);
function optionalText(value: unknown, max: number): string | null { if (value === undefined || value === null || value === "") return null; if (typeof value !== "string" || value.trim().length > max) throw new DrawingTakeoffPolicyError("TAKEOFF_TEXT_INVALID", "Takeoff text is invalid."); return value.trim(); }
export function validateDrawingUpload(file: File, intent: unknown) { if (file.type !== "application/pdf" || !file.name.toLowerCase().endsWith(".pdf")) throw new DrawingTakeoffPolicyError("DRAWING_FORMAT_UNSUPPORTED", "The V1 takeoff accepts PDF drawings only."); if (file.size <= 0 || file.size > MAX_DRAWING_BYTES) throw new DrawingTakeoffPolicyError("DRAWING_SIZE_INVALID", "Drawing must be between 1 byte and 15 MB."); const userIntent = optionalText(intent, 1000); if (!userIntent || userIntent.length < 5) throw new DrawingTakeoffPolicyError("DRAWING_INTENT_REQUIRED", "A bounded commercial intent is required."); return { sourceFileName: file.name.slice(0, 255), sourceMimeType: file.type, sourceSizeBytes: file.size, userIntent }; }
export function validateTakeoffLines(raw: unknown) { if (!Array.isArray(raw) || raw.length === 0 || raw.length > MAX_TAKEOFF_LINES) throw new DrawingTakeoffPolicyError("TAKEOFF_LINES_INVALID", `Provide 1 to ${MAX_TAKEOFF_LINES} takeoff lines.`); return raw.map((value, index) => { if (!value || typeof value !== "object" || Array.isArray(value)) throw new DrawingTakeoffPolicyError("TAKEOFF_LINE_INVALID", "Each takeoff line must be an object."); const line = value as TakeoffLineInput; const itemName = optionalText(line.itemName, 255); if (!itemName) throw new DrawingTakeoffPolicyError("TAKEOFF_ITEM_REQUIRED", "Each takeoff line requires an item name."); const quantity = line.quantity === null || line.quantity === "" || line.quantity === undefined ? null : Number(line.quantity); if (quantity !== null && (!Number.isFinite(quantity) || quantity <= 0 || quantity > 1_000_000)) throw new DrawingTakeoffPolicyError("TAKEOFF_QUANTITY_INVALID", "Quantity must be a positive bounded number."); const source = line.provenance; if (typeof source !== "string" || !provenance.has(source as TakeoffProvenance)) throw new DrawingTakeoffPolicyError("TAKEOFF_PROVENANCE_INVALID", "Quantity provenance is required."); const confidence = line.confidence === null || line.confidence === undefined ? null : Number(line.confidence); if (confidence !== null && (!Number.isFinite(confidence) || confidence < 0 || confidence > 1)) throw new DrawingTakeoffPolicyError("TAKEOFF_CONFIDENCE_INVALID", "Confidence must be between zero and one."); const isConfirmed = line.isConfirmed === true; if (isConfirmed && quantity === null) throw new DrawingTakeoffPolicyError("TAKEOFF_UNRESOLVED", "An unresolved quantity cannot be confirmed."); return { position: index + 1, itemName, description: optionalText(line.description, 2000), quantity, unitName: optionalText(line.unitName, 50), provenance: source as TakeoffProvenance, evidence: optionalText(line.evidence, 1000), confidence, isConfirmed }; }); }
export function assertTakeoffConfirmable(lines: Array<{ quantity: unknown; isConfirmed: boolean }>) { if (lines.length === 0 || lines.some((line) => line.quantity === null || line.quantity === undefined || !line.isConfirmed)) throw new DrawingTakeoffPolicyError("TAKEOFF_REVIEW_INCOMPLETE", "Every quantity must be resolved and explicitly confirmed."); }
