"use client";
import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { CommercialComposer, CommercialLineEditor, ComposerSection, createCommercialLine, type CommercialCatalogItem, type CommercialLineDraft } from "@/components/commercial";
import { useLanguage } from "@/components/i18n/LanguageProvider";
import { Button, Card, Input, SectionHeader } from "@/components/ui";
type Customer = { id: string; name: string; nameAr?: string | null; nameEn?: string | null };
type Origin = "DIRECT" | "QUOTATION" | "SALES_ORDER";
export default function NewInvoicePage() {
  const { isArabic } = useLanguage(); const router = useRouter(); const t = (ar: string, en: string) => isArabic ? ar : en;
  const [origin, setOrigin] = useState<Origin>("DIRECT"), [customers, setCustomers] = useState<Customer[]>([]), [items, setItems] = useState<CommercialCatalogItem[]>([]), [customerId, setCustomerId] = useState(""), [sourceId, setSourceId] = useState(""), [currencyCode, setCurrencyCode] = useState("KWD"), [invoiceDate, setInvoiceDate] = useState(() => new Date().toISOString().slice(0, 10)), [dueDate, setDueDate] = useState(""), [notes, setNotes] = useState(""), [terms, setTerms] = useState(""), [lines, setLines] = useState<CommercialLineDraft[]>(() => [createCommercialLine("invoice-line-1")]), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [error, setError] = useState(""); const requestKey = useRef(crypto.randomUUID());
  useEffect(() => { let cancelled = false; void (async () => { try { const responses = await Promise.all([fetch("/api/customers?pageSize=100"), fetch("/api/catalog/items?pageSize=100&isActive=true"), fetch("/api/companies/current")]); if (responses.some((response) => !response.ok)) throw new Error(t("تعذر تحميل بيانات المحرر", "Could not load composer data")); const [customerBody, itemBody, companyBody] = await Promise.all(responses.map((response) => response.json())); if (cancelled) return; setCustomers(customerBody.data?.customers ?? []); setItems((Array.isArray(itemBody.data) ? itemBody.data : []).map((item: any) => ({ id: item.id, name: item.name, code: item.code, type: item.type, salePrice: Number(item.salePrice ?? 0), description: item.description, unitName: item.unit?.symbol ?? item.unitName ?? "PCS", taxPercentage: Number(item.taxRate?.percentage ?? 0) }))); if (typeof companyBody.data?.defaultCurrency === "string") setCurrencyCode(companyBody.data.defaultCurrency); } catch (caught) { setError(caught instanceof Error ? caught.message : "Load failed"); } finally { if (!cancelled) setLoading(false); } })(); return () => { cancelled = true; }; }, [isArabic]);
  const totals = useMemo(() => lines.reduce((sum, line) => { const subtotal = line.quantity * line.unitPrice, tax = subtotal * line.taxPercentage / 100; return { subtotal: sum.subtotal + subtotal, tax: sum.tax + tax, total: sum.total + subtotal + tax }; }, { subtotal: 0, tax: 0, total: 0 }), [lines]);
  const money = (value: number) => new Intl.NumberFormat(isArabic ? "ar-KW" : "en-US", { style: "currency", currency: currencyCode }).format(value);
  async function submit(event: FormEvent) { event.preventDefault(); try { setSaving(true); setError(""); const payload = origin === "DIRECT" ? { customerId, invoiceDate, dueDate: dueDate || null, currencyCode, notes: notes || null, termsAndConditions: terms || null, lines: lines.map(({ key: _key, ...line }, index) => ({ ...line, position: index + 1, catalogItemId: line.catalogItemId || null, description: line.description || null, unitName: line.unitName || "PCS" })) } : { sourceKind: origin, sourceId: sourceId.trim(), invoiceDate, dueDate: dueDate || null }; const response = await fetch("/api/invoices", { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": requestKey.current }, body: JSON.stringify(payload) }); const body = await response.json().catch(() => null); if (!response.ok || !body?.data?.id) throw new Error(body?.error?.message ?? t("تعذر إنشاء الفاتورة", "Unable to create invoice")); router.push(`/dashboard/invoices/${body.data.id}`); } catch (caught) { setError(caught instanceof Error ? caught.message : t("حدث خطأ", "An error occurred")); } finally { setSaving(false); } }
  if (loading) return <Card><div className="h-72 animate-pulse rounded-2xl bg-white/5" /></Card>;
  const summary = <Card><h3 className="font-semibold">{t("ملخص الفاتورة", "Invoice summary")}</h3><dl className="mt-5 space-y-3 text-sm"><div className="flex justify-between text-slate-400"><dt>{t("الإجمالي قبل الضريبة", "Subtotal")}</dt><dd>{money(totals.subtotal)}</dd></div><div className="flex justify-between text-slate-400"><dt>{t("الضريبة التقديرية", "Estimated tax")}</dt><dd>{money(totals.tax)}</dd></div><div className="flex justify-between border-t border-white/10 pt-4 text-lg font-semibold text-sky-200"><dt>{t("الإجمالي التقديري", "Estimated total")}</dt><dd>{money(totals.total)}</dd></div></dl><p className="mt-4 text-xs leading-5 text-slate-500">{t("هذه معاينة فقط. يتحقق الخادم من القيم المحفوظة ويحسبها.", "Preview only. The server validates and calculates persisted values.")}</p><Button className="mt-5 w-full" type="submit" disabled={saving}>{saving ? t("جارٍ الحفظ...", "Saving…") : t("حفظ مسودة الفاتورة", "Save invoice draft")}</Button></Card>;
  return <section className="space-y-6" dir={isArabic ? "rtl" : "ltr"}><SectionHeader eyebrow={t("العمليات التجارية", "Commercial operations")} title={t("إنشاء فاتورة", "Create Invoice")} description={t("محرر تجاري متكامل مع بقاء الحساب والحفظ تحت سلطة الخادم.", "A complete commercial editor with calculation and persistence remaining server-authoritative.")} /><form onSubmit={submit}><CommercialComposer mode="INVOICE" isArabic={isArabic} title={t("مسودة فاتورة جديدة", "New invoice draft")} description={t("أنشئ فاتورة مباشرة أو من مستند مؤهل مع الحفاظ على تاريخه.", "Create directly or from an eligible source while preserving its history.")} summary={summary}>
    {error ? <Card className="border-red-400/20 bg-red-400/5"><p className="text-red-300">{error}</p></Card> : null}
    <ComposerSection title={t("المصدر والعميل", "Origin & customer")} description={t("اختر إنشاءً مباشرًا أو مصدرًا تجاريًا مؤهلًا.", "Choose direct creation or an eligible commercial source.")}><div className="grid gap-4 md:grid-cols-2"><label className="space-y-2"><span className="text-sm text-slate-400">{t("مصدر الفاتورة", "Invoice origin")}</span><select value={origin} onChange={(e) => setOrigin(e.target.value as Origin)} className="min-h-11 w-full rounded-xl border border-white/10 bg-slate-950 px-4"><option value="DIRECT">{t("فاتورة مباشرة", "Direct invoice")}</option><option value="QUOTATION">{t("عرض سعر معتمد", "Approved quotation")}</option><option value="SALES_ORDER">{t("أمر بيع مؤكد", "Confirmed sales order")}</option></select></label>{origin === "DIRECT" ? <label className="space-y-2"><span className="text-sm text-slate-400">{t("العميل", "Customer")}</span><select required value={customerId} onChange={(e) => setCustomerId(e.target.value)} className="min-h-11 w-full rounded-xl border border-white/10 bg-slate-950 px-4"><option value="">{t("اختر العميل", "Select customer")}</option>{customers.map((customer) => <option key={customer.id} value={customer.id}>{isArabic ? customer.nameAr || customer.name : customer.nameEn || customer.name}</option>)}</select></label> : <label className="space-y-2"><span className="text-sm text-slate-400">{origin === "QUOTATION" ? t("معرّف عرض السعر", "Quotation ID") : t("معرّف أمر البيع", "Sales Order ID")}</span><Input required value={sourceId} onChange={(e) => setSourceId(e.target.value)} /></label>}<label className="space-y-2"><span className="text-sm text-slate-400">{t("تاريخ الفاتورة", "Invoice date")}</span><Input required type="date" value={invoiceDate} onChange={(e) => setInvoiceDate(e.target.value)} /></label><label className="space-y-2"><span className="text-sm text-slate-400">{t("تاريخ الاستحقاق", "Due date")}</span><Input type="date" value={dueDate} onChange={(e) => setDueDate(e.target.value)} /></label></div></ComposerSection>
    {origin === "DIRECT" ? <><ComposerSection title={t("البنود التجارية", "Commercial lines")} description={t("منتج أو خدمة أو بند مخصص؛ راجع كل كمية وسعر.", "Product, service, or custom lines—review every quantity and price.")}><CommercialLineEditor lines={lines} items={items} isArabic={isArabic} currencyCode={currencyCode} onChange={setLines} /></ComposerSection><ComposerSection title={t("الملاحظات والشروط", "Notes & terms")}><div className="grid gap-4 md:grid-cols-2"><label className="space-y-2"><span className="text-sm text-slate-400">{t("ملاحظات", "Notes")}</span><textarea value={notes} onChange={(e) => setNotes(e.target.value)} className="min-h-32 w-full rounded-xl border border-white/10 bg-slate-950 p-4" /></label><label className="space-y-2"><span className="text-sm text-slate-400">{t("الشروط التجارية", "Commercial terms")}</span><textarea value={terms} onChange={(e) => setTerms(e.target.value)} className="min-h-32 w-full rounded-xl border border-white/10 bg-slate-950 p-4" /></label></div></ComposerSection></> : <Card className="border-amber-400/20 bg-amber-400/5"><p className="text-sm text-amber-100">{t("يأخذ الخادم العميل والبنود والأسعار والمرجع الدقيق من المستند المصدر؛ لا يمكن تعديلها هنا بصمت.", "The server copies customer, lines, prices, and exact provenance from the source; they cannot be silently edited here.")}</p></Card>}
  </CommercialComposer></form></section>;
}
