"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Button, Card, Input, SectionHeader } from "@/components/ui";
import { useLanguage } from "@/components/i18n/LanguageProvider";

type Customer={id:string;name:string};
type Line={position:number;type:"PRODUCT"|"SERVICE"|"CUSTOM";itemName:string;quantity:number;unitPrice:number};
export default function NewInvoicePage(){
 const {isArabic}=useLanguage();const router=useRouter();const [mode,setMode]=useState<"DIRECT"|"QUOTATION"|"SALES_ORDER">("DIRECT");const [customers,setCustomers]=useState<Customer[]>([]);const [customerId,setCustomerId]=useState("");const [sourceId,setSourceId]=useState("");const [dueDate,setDueDate]=useState("");const [lines,setLines]=useState<Line[]>([{position:1,type:"CUSTOM",itemName:"",quantity:1,unitPrice:0}]);const [saving,setSaving]=useState(false);const [error,setError]=useState("");
 useEffect(()=>{void fetch("/api/customers?pageSize=100").then(r=>r.json()).then(b=>setCustomers(b.data?.customers??b.data?.items??[])).catch(()=>setCustomers([]))},[]);
 const update=(i:number,key:keyof Line,value:string|number)=>setLines(current=>current.map((line,index)=>index===i?{...line,[key]:value}:line));
 async function submit(e:React.FormEvent){e.preventDefault();try{setSaving(true);setError("");const payload=mode==="DIRECT"?{customerId,dueDate:dueDate||null,currencyCode:"KWD",lines}:{sourceKind:mode,sourceId,dueDate:dueDate||null};const r=await fetch("/api/invoices",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify(payload)});const b=await r.json().catch(()=>null);if(!r.ok||!b?.data?.id)throw new Error(b?.error?.message??"Unable to create invoice");router.push(`/dashboard/invoices/${b.data.id}`)}catch(e){setError(e instanceof Error?e.message:"Error")}finally{setSaving(false)}}
 return <section className="space-y-6" dir={isArabic?"rtl":"ltr"}><SectionHeader eyebrow={isArabic?"فاتورة جديدة":"New invoice"} title={isArabic?"إنشاء مطالبة مالية":"Create financial claim"} description={isArabic?"أنشئ فاتورة مباشرة أو من مستند تجاري مؤهل.":"Create directly or from an eligible commercial source."}/>
 <form onSubmit={submit} className="space-y-5"><Card><label className="text-sm text-slate-400">{isArabic?"المصدر":"Origin"}</label><select value={mode} onChange={e=>setMode(e.target.value as any)} className="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3"><option value="DIRECT">{isArabic?"مباشرة":"Direct"}</option><option value="QUOTATION">{isArabic?"عرض سعر معتمد":"Approved quotation"}</option><option value="SALES_ORDER">{isArabic?"أمر بيع مؤكد":"Confirmed Sales Order"}</option></select>
 {mode==="DIRECT"?<div className="mt-4"><label className="text-sm text-slate-400">{isArabic?"العميل":"Customer"}</label><select required value={customerId} onChange={e=>setCustomerId(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3"><option value="">{isArabic?"اختر العميل":"Select customer"}</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div>:<div className="mt-4"><Input required value={sourceId} onChange={e=>setSourceId(e.target.value)} placeholder={isArabic?"معرف المستند المصدر":"Source document ID"}/></div>}
 <div className="mt-4"><label className="text-sm text-slate-400">{isArabic?"تاريخ الاستحقاق":"Due date"}</label><Input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)}/></div></Card>
 {mode==="DIRECT"&&<Card><h3 className="font-semibold">{isArabic?"بنود الفاتورة":"Invoice lines"}</h3>{lines.map((line,i)=><div key={i} className="mt-3 grid gap-3 md:grid-cols-4"><Input required value={line.itemName} onChange={e=>update(i,"itemName",e.target.value)} placeholder={isArabic?"اسم البند":"Item name"}/><Input type="number" min="0.001" step="0.001" value={line.quantity} onChange={e=>update(i,"quantity",Number(e.target.value))}/><Input type="number" min="0" step="0.001" value={line.unitPrice} onChange={e=>update(i,"unitPrice",Number(e.target.value))}/><Button type="button" variant="danger" disabled={lines.length===1} onClick={()=>setLines(v=>v.filter((_,x)=>x!==i).map((l,x)=>({...l,position:x+1})))}>{isArabic?"حذف":"Remove"}</Button></div>)}<Button type="button" variant="secondary" className="mt-4" onClick={()=>setLines(v=>[...v,{position:v.length+1,type:"CUSTOM",itemName:"",quantity:1,unitPrice:0}])}>{isArabic?"إضافة بند":"Add line"}</Button></Card>}
 {error&&<Card className="border-red-400/20"><p className="text-red-300">{error}</p></Card>}<Button type="submit" disabled={saving}>{saving?(isArabic?"جارٍ الحفظ...":"Saving..."):(isArabic?"إنشاء مسودة الفاتورة":"Create invoice draft")}</Button></form></section>
}
