"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { useLanguage } from "@/components/i18n/LanguageProvider";
type Report = { asOf: string; currencyCode: string; invoiceCount: number; totalOutstanding: string; buckets: Record<string, string>; invoices: Array<{ id: string; number: string; dueDate: string | null; overdueDays: number; bucket: string; outstandingAmount: string; customer: { name: string; nameAr: string | null; nameEn: string | null } }> };
const labels: Record<string, { en: string; ar: string }> = { CURRENT: { en: "Current", ar: "غير مستحق" }, DAYS_0_30: { en: "0–30 days", ar: "0–30 يومًا" }, DAYS_31_60: { en: "31–60 days", ar: "31–60 يومًا" }, DAYS_61_90: { en: "61–90 days", ar: "61–90 يومًا" }, DAYS_90_PLUS: { en: "90+ days", ar: "أكثر من 90 يومًا" } };
export default function ReportsPage() {
  const { isArabic } = useLanguage(); const [filters, setFilters] = useState({ currencyCode: "KWD", asOf: new Date().toISOString().slice(0, 10) }); const [report, setReport] = useState<Report | null>(null); const [error, setError] = useState(false); const [loading, setLoading] = useState(true);
  const load = useCallback(async (next: typeof filters) => { setLoading(true); setError(false); const response = await fetch(`/api/reports/receivables-aging?${new URLSearchParams(next)}`, { cache: "no-store" }); const payload = await response.json(); if (!response.ok) throw new Error(payload?.error?.message ?? "Report failed"); setReport(payload.data); setLoading(false); }, []);
  useEffect(() => { load({ currencyCode: "KWD", asOf: new Date().toISOString().slice(0, 10) }).catch(() => { setError(true); setLoading(false); }); }, [load]);
  const t = (ar: string, en: string) => isArabic ? ar : en; const money = (value: string) => new Intl.NumberFormat(isArabic ? "ar-KW" : "en-US", { style: "currency", currency: report?.currencyCode ?? filters.currencyCode, minimumFractionDigits: 3 }).format(Number(value));
  const submit = (event: FormEvent) => { event.preventDefault(); load(filters).catch(() => { setError(true); setLoading(false); }); };
  const exportXlsx = async () => {
    if (!report) return;
    const ExcelJS = await import("exceljs"); const workbook = new ExcelJS.Workbook(); workbook.creator = "VOKA"; workbook.created = new Date();
    const sheet = workbook.addWorksheet(isArabic ? "أعمار الذمم" : "Receivables Aging", { views: [{ rightToLeft: isArabic }] });
    sheet.columns = [{ header: t("الفاتورة", "Invoice"), key: "invoice", width: 20 }, { header: t("العميل", "Customer"), key: "customer", width: 32 }, { header: t("الاستحقاق", "Due"), key: "due", width: 16 }, { header: t("التأخير", "Overdue days"), key: "days", width: 16 }, { header: t("الفئة", "Bucket"), key: "bucket", width: 18 }, { header: `${t("المستحق", "Outstanding")} (${report.currencyCode})`, key: "outstanding", width: 22 }];
    report.invoices.forEach((invoice) => sheet.addRow({ invoice: invoice.number, customer: isArabic ? invoice.customer.nameAr ?? invoice.customer.nameEn ?? invoice.customer.name : invoice.customer.nameEn ?? invoice.customer.nameAr ?? invoice.customer.name, due: invoice.dueDate?.slice(0, 10) ?? "", days: invoice.overdueDays, bucket: isArabic ? labels[invoice.bucket].ar : labels[invoice.bucket].en, outstanding: Number(invoice.outstandingAmount) }));
    sheet.getRow(1).font = { bold: true, color: { argb: "FFFFFFFF" } }; sheet.getRow(1).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF075985" } }; sheet.autoFilter = { from: "A1", to: "F1" }; sheet.views = [{ state: "frozen", ySplit: 1, rightToLeft: isArabic }]; sheet.getColumn("outstanding").numFmt = "#,##0.000";
    const summary = workbook.addWorksheet(isArabic ? "الملخص" : "Summary", { views: [{ rightToLeft: isArabic }] }); summary.addRows([[t("حتى تاريخ", "As of"), report.asOf.slice(0,10)], [t("العملة", "Currency"), report.currencyCode], [t("عدد الفواتير", "Invoice count"), report.invoiceCount], [t("إجمالي المستحق", "Total outstanding"), Number(report.totalOutstanding)], ...Object.entries(report.buckets).map(([key,value]) => [isArabic ? labels[key].ar : labels[key].en, Number(value)])]); summary.getColumn(1).width=30; summary.getColumn(2).width=22; summary.getColumn(2).numFmt="#,##0.000";
    const buffer = await workbook.xlsx.writeBuffer(); const url = URL.createObjectURL(new Blob([buffer], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" })); const link = document.createElement("a"); link.href=url; link.download=`voka-receivables-${filters.asOf}-${report.currencyCode}.xlsx`; link.click(); URL.revokeObjectURL(url);
  };
  return <section className="space-y-6" dir={isArabic ? "rtl" : "ltr"}><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="text-sm font-semibold text-sky-300">{t("التقارير الإدارية", "Management reporting")}</p><h1 className="mt-2 text-3xl font-bold">{t("أعمار الذمم المدينة", "Receivables aging")}</h1><p className="mt-2 text-slate-400">{t("الفواتير الصادرة غير المسددة حسب تاريخ الاستحقاق.", "Issued unsettled invoices grouped by due date.")}</p></div><div className="flex gap-3"><button type="button" disabled={!report} onClick={() => void exportXlsx()} className="rounded-xl border border-emerald-700 px-4 py-2 text-emerald-200 disabled:opacity-40">{t("تصدير Excel", "Export Excel")}</button><Link href="/dashboard/invoices" className="rounded-xl border border-slate-700 px-4 py-2">{t("الفواتير والمدفوعات", "Invoices & Payments")}</Link></div></div>
    <form onSubmit={submit} className="grid gap-4 rounded-2xl border border-slate-800 bg-slate-900 p-5 sm:grid-cols-3"><label>{t("حتى تاريخ", "As of")}<input type="date" value={filters.asOf} onChange={(e) => setFilters({ ...filters, asOf: e.target.value })} className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2" /></label><label>{t("العملة", "Currency")}<input maxLength={3} value={filters.currencyCode} onChange={(e) => setFilters({ ...filters, currencyCode: e.target.value.toUpperCase() })} className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2" /></label><button disabled={loading} className="self-end rounded-lg bg-sky-600 px-4 py-2 font-semibold disabled:opacity-50">{t("تحديث", "Update")}</button></form>
    {error ? <div role="alert" className="rounded-xl border border-red-800 bg-red-950/30 p-4 text-red-200">{t("تعذر تحميل التقرير.", "Unable to load report.")}</div> : null}
    {report ? <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6"><div className="rounded-2xl border border-sky-700/40 bg-sky-950/20 p-5"><p className="text-sm text-slate-400">{t("إجمالي المستحق", "Total outstanding")}</p><p className="mt-2 text-xl font-bold">{money(report.totalOutstanding)}</p><p className="mt-1 text-xs text-slate-500">{report.invoiceCount} {t("فاتورة", "invoices")}</p></div>{Object.entries(report.buckets).map(([key, value]) => <div key={key} className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><p className="text-sm text-slate-400">{isArabic ? labels[key].ar : labels[key].en}</p><p className="mt-2 text-xl font-bold">{money(value)}</p></div>)}</div><div className="overflow-x-auto rounded-2xl border border-slate-800"><table className="w-full min-w-[760px] text-sm"><thead className="bg-slate-900"><tr>{[t("الفاتورة", "Invoice"), t("العميل", "Customer"), t("الاستحقاق", "Due"), t("التأخير", "Overdue"), t("الفئة", "Bucket"), t("المستحق", "Outstanding")].map((item) => <th key={item} className="px-4 py-3 text-start">{item}</th>)}</tr></thead><tbody>{report.invoices.map((invoice) => <tr key={invoice.id} className="border-t border-slate-800"><td className="px-4 py-3"><Link className="text-sky-300" href={`/dashboard/invoices/${invoice.id}`}>{invoice.number}</Link></td><td className="px-4 py-3">{isArabic ? invoice.customer.nameAr ?? invoice.customer.nameEn ?? invoice.customer.name : invoice.customer.nameEn ?? invoice.customer.nameAr ?? invoice.customer.name}</td><td className="px-4 py-3">{invoice.dueDate ? new Intl.DateTimeFormat(isArabic ? "ar-KW" : "en-GB").format(new Date(invoice.dueDate)) : "—"}</td><td className="px-4 py-3">{invoice.overdueDays}</td><td className="px-4 py-3">{isArabic ? labels[invoice.bucket].ar : labels[invoice.bucket].en}</td><td className="px-4 py-3 font-semibold">{money(invoice.outstandingAmount)}</td></tr>)}</tbody></table></div></> : null}
  </section>;
}
