import ExcelJS from 'exceljs'; import { NextResponse } from 'next/server'; import { ApiError, withCompanyAuth } from '@/lib/api'; import { getCustomerActivitySnapshot } from '@/lib/reporting/customer-activity';
export const runtime = 'nodejs'; export const dynamic = 'force-dynamic';
function customerId(request: Request) { const parts = new URL(request.url).pathname.split('/').filter(Boolean); const index = parts.indexOf('activity'); const value = decodeURIComponent(parts[index - 1] ?? ''); if (!value) throw ApiError.badRequest('CUSTOMER_ID_REQUIRED', 'customerId is required.'); return value; }
export const GET = withCompanyAuth(['OWNER', 'ADMIN', 'SALES', 'VIEWER'], async (request, auth, company) => { const snapshot = await getCustomerActivitySnapshot(company.companyId, customerId(request), 'EXPORT'); const ar = auth.user.locale.startsWith('ar'); const t = (a: string, e: string) => ar ? a : e; const book = new ExcelJS.Workbook(); book.creator = 'VOKA'; book.created = new Date(snapshot.generatedAt);
  const add = (name: string, headers: string[], rows: unknown[][], money: number[] = [], dates: number[] = []) => { const sheet = book.addWorksheet(name, { views: [{ rightToLeft: ar, state: 'frozen', ySplit: 1 }] }); sheet.addRow(headers); rows.forEach((row) => sheet.addRow(row)); sheet.getRow(1).font = { bold: true }; sheet.columns = headers.map(() => ({ width: 21 })); money.forEach((column) => { sheet.getColumn(column).numFmt = '#,##0.000'; }); dates.forEach((column) => { sheet.getColumn(column).numFmt = 'yyyy-mm-dd'; }); sheet.autoFilter = { from: { row: 1, column: 1 }, to: { row: 1, column: headers.length } }; };
  add(t('عروض الأسعار', 'Quotations'), ['Reference', 'Date', 'Expiry', 'Status', 'Amount', 'Currency', 'Family', 'Revision', 'Previous revision ID'], snapshot.quotations.records.map((r) => [r.number, new Date(r.issueDate), r.expiryDate ? new Date(r.expiryDate) : null, r.status, r.totalAmount, r.currencyCode, r.familyId, r.revisionNumber, r.previousRevisionId]), [5], [2, 3]);
  add(t('أوامر البيع', 'Sales Orders'), ['Reference', 'Date', 'Status', 'Amount', 'Currency', 'Source quotation', 'Source quotation ID', 'Quotation family', 'Quotation revision'], snapshot.salesOrders.records.map((r) => [r.number, new Date(r.orderDate), r.status, r.totalAmount, r.currencyCode, r.sourceQuotationNumber, r.sourceQuotationId, r.sourceQuotationFamilyId, r.sourceQuotationRevisionNumber]), [4], [2]);
  add(t('العقود', 'Contracts'), ['Reference', 'Contract date', 'Start date', 'End date', 'Status', 'Amount', 'Currency', 'Origin', 'Source kind', 'Source ID'], snapshot.contracts.records.map((r) => [r.number, new Date(r.contractDate), r.startDate ? new Date(r.startDate) : null, r.endDate ? new Date(r.endDate) : null, r.status, r.totalAmount, r.currencyCode, r.origin, r.sourceKind, r.sourceId]), [6], [2, 3, 4]);
  add(t('الفواتير', 'Invoices'), ['Reference', 'Invoice date', 'Due date', 'Status', 'Settlement', 'Total', 'Paid', 'Outstanding', 'Currency', 'Origin', 'Source kind', 'Source ID', 'Quotation family', 'Quotation revision'], snapshot.invoices.records.map((r) => [r.number, new Date(r.invoiceDate), r.dueDate ? new Date(r.dueDate) : null, r.status, r.settlementStatus, r.totalAmount, r.paidAmount, r.outstandingAmount, r.currencyCode, r.origin, r.sourceKind, r.sourceId, r.sourceQuotationFamilyId, r.sourceQuotationRevisionNumber]), [6, 7, 8], [2, 3]);
  add(t('المدفوعات', 'Payments'), ['Reference', 'Date', 'Method', 'Amount', 'Currency', 'Invoice', 'Invoice ID'], snapshot.payments.records.map((r) => [r.reference, new Date(r.receivedAt), r.method, r.amount, r.currencyCode, r.invoice.number, r.invoice.id]), [4], [2]);
  const summary = book.addWorksheet(t('ملخص العملات', 'Currency Summary'), { views: [{ rightToLeft: ar }] }); summary.addRow(['Module', 'Currency', 'Count', 'Total', 'Paid', 'Outstanding']); for (const [module, groups] of [['Quotations', snapshot.quotations.totals], ['Sales Orders', snapshot.salesOrders.totals], ['Contracts', snapshot.contracts.totals], ['Invoices', snapshot.invoices.totals], ['Payments', snapshot.payments.totals]] as const) for (const group of groups) summary.addRow([module, group.currencyCode, group.count, 'totalAmount' in group ? group.totalAmount : 'amount' in group ? group.amount : 0, 'paidAmount' in group ? group.paidAmount : null, 'outstandingAmount' in group ? group.outstandingAmount : null]); summary.getRow(1).font = { bold: true }; summary.columns = [{ width: 20 }, { width: 12 }, { width: 12 }, { width: 18 }, { width: 18 }, { width: 18 }]; for (const column of [4, 5, 6]) summary.getColumn(column).numFmt = '#,##0.000';
  const bytes = await book.xlsx.writeBuffer(); return new NextResponse(Buffer.from(bytes), { headers: { 'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'Content-Disposition': `attachment; filename="customer-activity-${snapshot.customer.code}.xlsx"`, 'Cache-Control': 'private, no-store', 'X-Content-Type-Options': 'nosniff' } }); });
