import type { Contract } from "@/src/domain/contract";

export function serializeContract(contract: Contract) {
  return {
    id: contract.id,
    companyId: contract.companyId,
    number: contract.number.value,
    status: contract.status,
    provenance: {
      origin: contract.provenance.origin,
      sourceKind: contract.provenance.sourceKind,
      sourceId: contract.provenance.sourceId,
    },
    customerId: contract.customerId,
    priceListId: contract.priceListId,
    currencyCode: contract.currencyCode,
    contractDate: contract.contractDate.toISOString(),
    startDate: contract.startDate?.toISOString() || null,
    endDate: contract.endDate?.toISOString() || null,
    customer: {
      name: contract.customer.name,
      nameAr: contract.customer.nameAr || null,
      nameEn: contract.customer.nameEn || null,
      email: contract.customer.email || null,
      phone: contract.customer.phone || null,
      taxNumber: contract.customer.taxNumber || null,
      billingAddress: contract.customer.billingAddress || null,
    },
    subjectAr: contract.subjectAr,
    subjectEn: contract.subjectEn,
    briefAr: contract.briefAr,
    briefEn: contract.briefEn,
    projectName: contract.projectName,
    projectNameAr: contract.projectNameAr,
    projectNameEn: contract.projectNameEn,
    attentionName: contract.attentionName,
    attentionNameAr: contract.attentionNameAr,
    attentionNameEn: contract.attentionNameEn,
    scopeType: contract.scopeType,
    subtotal: contract.subtotal,
    discountType: contract.discountType,
    discountValue: contract.discountValue,
    discountAmount: contract.discountAmount,
    taxAmount: contract.taxAmount,
    totalAmount: contract.totalAmount,
    lines: contract.lines.map((line) => ({
      id: line.id,
      sourceLineId: line.sourceLineId || null,
      catalogItemId: line.catalogItemId || null,
      taxRateId: line.taxRateId || null,
      position: line.position,
      type: line.type,
      itemCode: line.itemCode || null,
      itemName: line.itemName,
      itemNameAr: line.itemNameAr || null,
      itemNameEn: line.itemNameEn || null,
      description: line.description || null,
      descriptionAr: line.descriptionAr || null,
      descriptionEn: line.descriptionEn || null,
      unitName: line.unitName || null,
      unitNameAr: line.unitNameAr || null,
      unitNameEn: line.unitNameEn || null,
      quantity: line.quantity,
      unitPrice: line.unitPrice,
      discountType: line.discountType || null,
      discountValue: line.discountValue,
      discountAmount: line.discountAmount,
      taxPercentage: line.taxPercentage,
      taxAmount: line.taxAmount,
      subtotal: line.subtotal,
      totalAmount: line.totalAmount,
    })),
    milestones: contract.milestones.map((m) => m.toSnapshot()),
    notes: contract.notes,
    notesAr: contract.notesAr,
    notesEn: contract.notesEn,
    termsAndConditions: contract.termsAndConditions,
    termsAndConditionsAr: contract.termsAndConditionsAr,
    termsAndConditionsEn: contract.termsAndConditionsEn,
    createdByUserId: contract.createdByUserId,
    createdByName: contract.createdByName,
    createdByRole: contract.createdByRole,
    createdAt: contract.createdAt ? contract.createdAt.toISOString() : undefined,
    updatedAt: contract.updatedAt ? contract.updatedAt.toISOString() : undefined,
  };
}
