"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { LanguageSwitcher } from "../ui/LanguageSwitcher";
import { DEFAULT_LOCALE, getDirection, type Locale } from "../../lib/i18n";
import { VoiceOrb } from "../voice";

const COPY = {
  en: {
    eyebrow: "Voice-first AI Sales OS", headline: "From speech and drawings to intelligent commercial execution.",
    lead: "VOKA understands speech, text, commercial requests, and bounded drawing takeoffs—then prepares reviewable quotations, contracts, orders, invoices, and payment workflows.",
    signIn: "Sign in", explore: "See how it works", request: "Customer request", draft: "Draft for review",
    example: "I need a quotation to supply and install 8 cameras for a villa.",
    proof: ["Human approval before every commercial commitment", "Arabic and English documents", "Deterministic quantities and server-authoritative totals"],
    flowTitle: "From request to receivable", flowLead: "VOKA keeps commercial work simple without hiding control or inventing facts.",
    steps: [["Speak or type", "Capture the customer request naturally in Arabic or English."], ["Review the draft", "Resolve customers and catalog items, then verify quantities, prices, tax, and terms."], ["Run the lifecycle", "Approve, deliver, convert, invoice, and record settlement with a complete history."]],
    capabilitiesTitle: "One commercial workspace",
    capabilities: [["Smart quotations", "Editable bilingual drafts with explicit provenance and approval controls."], ["System builder", "Versioned deterministic rules for CCTV, gypsum, and access-control scopes."], ["Sales lifecycle", "Quotation revisions, Sales Orders, Contracts, Invoices, and Payments."], ["Trusted catalog", "Tenant catalog plus governed universal retrieval—without loading a global library into the browser."]],
    finalTitle: "Less administration. More commercial clarity.", finalLead: "Enter your secure workspace and continue from the customer request to collection.", nav: "Main navigation",
    navItems: [["Product", "#product"], ["Drawing Intelligence", "#drawing"], ["Commercial Operations", "#workflow"], ["How it Works", "#workflow"], ["Commercial Knowledge", "#product"], ["About VOKA", "#trust"], ["Contact", "#contact"]],
    examples: ["Create a quotation to supply and install 8 cameras.", "Create a customer invoice for…", "Prepare a supply and installation contract.", "Record a payment against the invoice.", "Find the camera system in this drawing and prepare a quotation."],
    drawingTitle: "From drawing to quotation", drawingLead: "A bounded PDF and CCTV / Low Voltage technical preview: detected observations become editable quantities, catalog candidates, and a commercial draft.", drawingWarning: "Uncertain quantities stay visible and require human review before approval.", preview: "Technical preview", trust: ["AI understands.", "Rules calculate.", "Human approves."],
  },
  ar: {
    eyebrow: "نظام تشغيل مبيعات ذكي يبدأ بالصوت", headline: "من الكلام والمخططات إلى تنفيذ تجاري ذكي.",
    lead: "يفهم VOKA الصوت والنص والطلبات التجارية والحصر المحدود من المخططات، ثم يجهّز عروض الأسعار والعقود والأوامر والفواتير والتحصيل للمراجعة البشرية.",
    signIn: "تسجيل الدخول", explore: "اعرف كيف تعمل فوكا", request: "طلب العميل", draft: "مسودة للمراجعة",
    example: "أحتاج عرض سعر لتوريد وتركيب 8 كاميرات لفيلا.",
    proof: ["اعتماد بشري قبل أي التزام تجاري", "مستندات عربية وإنجليزية", "كميات حتمية وإجماليات يحسبها الخادم"],
    flowTitle: "من طلب العميل إلى التحصيل", flowLead: "تجعل فوكا العمل التجاري بسيطًا من دون إخفاء التحكم أو اختلاق المعلومات.",
    steps: [["تكلّم أو اكتب", "سجّل طلب العميل بطبيعته بالعربية أو الإنجليزية."], ["راجع المسودة", "ثبّت العميل والأصناف، ثم راجع الكميات والأسعار والضريبة والشروط."], ["أكمل الدورة التجارية", "اعتمد وأرسل وحوّل إلى أمر بيع، ثم أصدر الفاتورة وسجّل التحصيل بتاريخ كامل."]],
    capabilitiesTitle: "مساحة واحدة للعمل التجاري",
    capabilities: [["عروض أسعار ذكية", "مسودات ثنائية اللغة قابلة للتعديل، مع مصدر واضح وضوابط اعتماد."], ["بناء الأنظمة", "قواعد هندسية حتمية ومُرقّمة لأنظمة الكاميرات والجبس والتحكم بالدخول."], ["دورة المبيعات", "مراجعات عروض الأسعار وأوامر البيع والعقود والفواتير والمدفوعات."], ["كتالوج موثوق", "كتالوج الشركة مع بحث عالمي محكوم، من دون تحميل المكتبة كاملة في المتصفح."]],
    finalTitle: "إدارة أقل. وضوح تجاري أكبر.", finalLead: "ادخل مساحة العمل الآمنة وأكمل الرحلة من طلب العميل حتى التحصيل.", nav: "التنقل الرئيسي",
    navItems: [["المنتج", "#product"], ["ذكاء المخططات", "#drawing"], ["العمليات التجارية", "#workflow"], ["كيف يعمل", "#workflow"], ["المعرفة التجارية", "#product"], ["عن VOKA", "#trust"], ["تواصل معنا", "#contact"]],
    examples: ["اعمل عرض سعر لتوريد وتركيب 8 كاميرات للعميل.", "أنشئ فاتورة للعميل بقيمة محددة.", "جهّز عقد توريد وتركيب.", "سجّل دفعة على الفاتورة.", "استخرج نظام الكاميرات من المخطط وجهّز مسودة عرض سعر."],
    drawingTitle: "من المخطط إلى عرض السعر", drawingLead: "معاينة تقنية محدودة لملفات PDF وأنظمة الكاميرات والتيار الخفيف: تتحول الملاحظات إلى كميات قابلة للتعديل ومرشحات كتالوج ومسودة تجارية.", drawingWarning: "تظل الكميات غير المؤكدة ظاهرة، ولا تعتمد قبل المراجعة البشرية.", preview: "معاينة تقنية قيد التطوير", trust: ["الذكاء يفهم.", "القواعد تحسب.", "الإنسان يعتمد."],
  },
} as const;

export function LandingPageV1() {
  const [locale, setLocale] = useState<Locale>(DEFAULT_LOCALE);
  useEffect(() => { const stored = window.localStorage.getItem("voka-locale"); if (stored === "ar" || stored === "en") setLocale(stored); }, []);
  useEffect(() => { window.localStorage.setItem("voka-locale", locale); document.documentElement.lang = locale; document.documentElement.dir = getDirection(locale); }, [locale]);
  const c = COPY[locale];
  return <main dir={getDirection(locale)} className="min-h-screen overflow-hidden bg-slate-950 text-slate-100">
    <header className="sticky top-0 z-40 border-b border-white/10 bg-slate-950/80 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4 sm:px-10 lg:px-14"><Link href="/" aria-label="VOKA home" className="text-2xl font-bold tracking-[0.16em]">VOKA</Link><nav aria-label={c.nav} className="hidden items-center gap-5 text-xs text-slate-300 xl:flex">{c.navItems.map(([label, href]) => <a key={label} href={href} className="hover:text-sky-200">{label}</a>)}</nav><div className="flex items-center gap-3"><LanguageSwitcher locale={locale} onChange={setLocale} /><Link href="/login" className="rounded-full border border-sky-400/60 px-5 py-2.5 text-sm font-semibold text-sky-100 hover:bg-sky-400/10">{c.signIn}</Link></div></div></header>
    <section className="relative mx-auto grid max-w-7xl gap-12 px-6 pb-24 pt-14 sm:px-10 lg:grid-cols-[1.12fr_.88fr] lg:items-center lg:px-14 lg:pt-24"><div className="absolute -top-32 end-0 h-96 w-96 rounded-full bg-sky-500/10 blur-3xl" /><div className="relative"><p className="text-sm font-semibold uppercase tracking-[0.24em] text-sky-300">{c.eyebrow}</p><h1 className="mt-6 max-w-4xl text-5xl font-bold leading-[1.08] tracking-tight sm:text-6xl lg:text-7xl">{c.headline}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-300 sm:text-xl">{c.lead}</p><div className="mt-9 flex flex-wrap gap-4"><Link href="/login" className="rounded-full bg-sky-400 px-7 py-3.5 font-bold text-slate-950 hover:bg-sky-300">{c.signIn}</Link><a href="#workflow" className="rounded-full border border-slate-700 px-7 py-3.5 font-semibold hover:border-slate-500">{c.explore}</a></div></div><aside className="relative overflow-hidden rounded-[2rem] border border-sky-300/20 bg-gradient-to-br from-slate-900 via-slate-950 to-indigo-950 p-6 shadow-2xl shadow-sky-950/50 sm:p-8"><div className="mx-auto flex justify-center"><VoiceOrb size="hero" label={locale === "ar" ? "رمز VOKA الصوتي" : "VOKA voice orb"} /></div><div className="mt-3 rounded-2xl border border-sky-400/20 bg-slate-950/80 p-5"><p className="text-sm text-sky-300">{c.request}</p><p className="mt-3 text-lg leading-8">{c.example}</p></div><div className="my-5 flex items-center gap-3 text-sm text-slate-400"><span className="h-px flex-1 bg-slate-700" /><span>{c.draft}</span><span className="h-px flex-1 bg-slate-700" /></div><div className="grid gap-2">{c.examples.slice(1,4).map((item) => <div key={item} className="rounded-xl bg-white/[0.04] p-3 text-sm text-slate-300">{item}</div>)}</div></aside></section>
    <section id="workflow" className="border-y border-white/10 bg-slate-900/35"><div className="mx-auto max-w-7xl px-6 py-20 sm:px-10 lg:px-14"><div className="max-w-3xl"><h2 className="text-3xl font-bold sm:text-4xl">{c.flowTitle}</h2><p className="mt-4 text-lg leading-8 text-slate-400">{c.flowLead}</p></div><ol className="mt-10 grid gap-5 lg:grid-cols-3">{c.steps.map(([title, description], index) => <li key={title} className="rounded-3xl border border-white/10 bg-slate-950 p-6"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-sky-400 font-bold text-slate-950">{index + 1}</span><h3 className="mt-5 text-xl font-bold">{title}</h3><p className="mt-3 leading-7 text-slate-400">{description}</p></li>)}</ol></div></section>
    <section id="drawing" className="mx-auto max-w-7xl px-6 py-20 sm:px-10 lg:px-14"><div className="grid gap-8 rounded-[2rem] border border-cyan-300/20 bg-gradient-to-br from-slate-900 to-indigo-950/60 p-7 lg:grid-cols-[.9fr_1.1fr] lg:p-10"><div><span className="rounded-full border border-amber-300/30 bg-amber-300/10 px-3 py-1 text-xs text-amber-200">{c.preview}</span><h2 className="mt-5 text-3xl font-bold sm:text-4xl">{c.drawingTitle}</h2><p className="mt-4 leading-8 text-slate-300">{c.drawingLead}</p><p className="mt-5 rounded-xl border border-sky-300/20 bg-sky-300/5 p-4 text-sm text-sky-100">{c.drawingWarning}</p></div><div className="relative min-h-72 overflow-hidden rounded-2xl border border-sky-300/20 bg-[linear-gradient(rgba(56,189,248,.08)_1px,transparent_1px),linear-gradient(90deg,rgba(56,189,248,.08)_1px,transparent_1px)] bg-[size:24px_24px] p-5"><div className="grid h-full gap-3 sm:grid-cols-2"><div className="rounded-xl border border-cyan-300/30 bg-slate-950/80 p-4"><p className="text-xs text-cyan-300">01 · PDF</p><p className="mt-3">{c.examples[4]}</p></div><div className="rounded-xl border border-violet-300/30 bg-slate-950/80 p-4"><p className="text-xs text-violet-300">02 · {locale === "ar" ? "كميات للمراجعة" : "Reviewable quantities"}</p><div className="mt-3 space-y-2 text-sm"><p>Camera · 8 · ✓</p><p>Cable · — · ?</p><p>NVR · 1 · ✓</p></div></div><div className="rounded-xl border border-sky-300/30 bg-slate-950/80 p-4 sm:col-span-2"><p className="text-xs text-sky-300">03 · {locale === "ar" ? "ربط الكتالوج ← مسودة تجارية" : "Catalog mapping → commercial draft"}</p></div></div></div></div></section>
    <section id="product" className="mx-auto max-w-7xl px-6 py-20 sm:px-10 lg:px-14"><h2 className="text-3xl font-bold sm:text-4xl">{c.capabilitiesTitle}</h2><div className="mt-10 grid gap-5 md:grid-cols-2">{c.capabilities.map(([title, description]) => <article key={title} className="rounded-3xl border border-white/10 p-6"><h3 className="text-xl font-bold">{title}</h3><p className="mt-3 leading-7 text-slate-400">{description}</p></article>)}</div></section>
    <section id="trust" className="mx-auto max-w-7xl px-6 pb-20 sm:px-10 lg:px-14"><div className="grid gap-4 md:grid-cols-3">{c.trust.map((item, index) => <div key={item} className="rounded-2xl border border-sky-300/15 bg-sky-300/[0.04] p-6 text-center text-xl font-semibold"><span className="block text-xs text-sky-300">0{index + 1}</span><span className="mt-3 block">{item}</span></div>)}</div></section>
    <section className="px-6 pb-20 sm:px-10 lg:px-14"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-7 rounded-[2rem] bg-sky-400 p-8 text-slate-950 sm:p-10 lg:flex-row lg:items-center"><div><h2 className="text-3xl font-bold">{c.finalTitle}</h2><p className="mt-3 max-w-2xl text-lg leading-8 text-slate-800">{c.finalLead}</p></div><Link href="/login" className="shrink-0 rounded-full bg-slate-950 px-7 py-3.5 font-bold text-white hover:bg-slate-800">{c.signIn}</Link></div></section>
    <footer id="contact" className="border-t border-white/10 px-6 py-8 text-sm text-slate-500 sm:px-10 lg:px-14"><div className="mx-auto flex max-w-7xl justify-between gap-5"><span>VOKA</span><span>© 2026</span></div></footer>
  </main>;
}
