"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { useLanguage } from "@/components/i18n/LanguageProvider";

type Statement = { customer: { id: string; code: string; name: string; nameAr: string | null; nameEn: string | null }; currencyCode: string; openingBalance: string; closingBalance: string; outstandingBalance: string; entries: Array<{ id: string; kind: "INVOICE" | "PAYMENT"; date: string; reference: string; debit: string; credit: string; runningBalance: string }> };
function today() { return new Date().toISOString().slice(0, 10); }

export default function CustomerStatementPage() {
  const { customerId } = useParams<{ customerId: string }>(); const { isArabic } = useLanguage(); const year = new Date().getUTCFullYear();
  const [filters, setFilters] = useState({ from: `${year}-01-01`, to: today(), currencyCode: "KWD" }); const [statement, setStatement] = useState<Statement | null>(null); const [state, setState] = useState<"loading" | "ready" | "error">("loading");
  const load = useCallback(async (next: typeof filters) => { setState("loading"); const query = new URLSearchParams(next); const response = await fetch(`/api/customers/${encodeURIComponent(customerId)}/statement?${query}`, { cache: "no-store" }); const payload = await response.json(); if (!response.ok) throw new Error(payload?.error?.message ?? "Unable to load statement."); setStatement(payload.data); setState("ready"); }, [customerId]);
  useEffect(() => { load({ from: `${year}-01-01`, to: today(), currencyCode: "KWD" }).catch(() => setState("error")); }, [load, year]);
  const t = (ar: string, en: string) => isArabic ? ar : en; const money = (value: string) => new Intl.NumberFormat(isArabic ? "ar-KW" : "en-US", { style: "currency", currency: statement?.currencyCode ?? filters.currencyCode, minimumFractionDigits: 3 }).format(Number(value));
  const submit = (event: FormEvent) => { event.preventDefault(); load(filters).catch(() => setState("error")); };
  return <section className="space-y-6 print:bg-white print:text-black" dir={isArabic ? "rtl" : "ltr"}>
    <div className="flex flex-col justify-between gap-4 print:block lg:flex-row lg:items-end"><div><p className="text-sm font-semibold text-sky-300">{statement?.customer.code ?? t("كشف حساب", "Statement")}</p><h1 className="mt-2 text-3xl font-bold">{t("كشف حساب العميل", "Customer statement")}</h1><p className="mt-2 text-slate-400 print:text-slate-700">{statement ? (isArabic ? statement.customer.nameAr ?? statement.customer.nameEn ?? statement.customer.name : statement.customer.nameEn ?? statement.customer.nameAr ?? statement.customer.name) : t("جارٍ التحميل...", "Loading...")}</p></div><div className="flex gap-3 print:hidden"><Link href={`/dashboard/customers/${encodeURIComponent(customerId)}`} className="rounded-xl border border-slate-700 px-4 py-2">{t("العميل", "Customer")}</Link><button onClick={() => window.print()} className="rounded-xl bg-sky-600 px-4 py-2 font-semibold">{t("طباعة / PDF", "Print / PDF")}</button></div></div>
    <form onSubmit={submit} className="grid gap-4 rounded-2xl border border-slate-800 bg-slate-900 p-5 print:hidden md:grid-cols-4"><label>{t("من", "From")}<input type="date" value={filters.from} onChange={(e) => setFilters({ ...filters, from: e.target.value })} className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2" /></label><label>{t("إلى", "To")}<input type="date" value={filters.to} onChange={(e) => setFilters({ ...filters, to: e.target.value })} className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2" /></label><label>{t("العملة", "Currency")}<input value={filters.currencyCode} maxLength={3} onChange={(e) => setFilters({ ...filters, currencyCode: e.target.value.toUpperCase() })} className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2" /></label><button disabled={state === "loading"} className="self-end rounded-lg bg-sky-600 px-4 py-2 font-semibold disabled:opacity-50">{t("تحديث", "Update")}</button></form>
    {state === "error" ? <div role="alert" className="rounded-xl border border-red-800 bg-red-950/30 p-4 text-red-200">{t("تعذر تحميل كشف الحساب. تحقق من الفترة والعملة.", "Unable to load the statement. Check the period and currency.")}</div> : null}
    {statement ? <><div className="grid gap-4 sm:grid-cols-3">{[[t("الرصيد الافتتاحي", "Opening balance"), statement.openingBalance], [t("الرصيد الختامي", "Closing balance"), statement.closingBalance], [t("الرصيد المستحق", "Outstanding balance"), statement.outstandingBalance]].map(([label, value]) => <div key={label} className="rounded-2xl border border-slate-800 bg-slate-900 p-5 print:border-slate-300 print:bg-white"><p className="text-sm text-slate-400 print:text-slate-600">{label}</p><p className="mt-2 text-2xl font-bold">{money(value)}</p></div>)}</div><div className="overflow-x-auto rounded-2xl border border-slate-800 print:border-slate-300"><table className="w-full min-w-[760px] text-sm"><thead className="bg-slate-900 text-slate-300 print:bg-slate-100 print:text-black"><tr>{[t("التاريخ", "Date"), t("النوع", "Type"), t("المرجع", "Reference"), t("مدين", "Debit"), t("دائن", "Credit"), t("الرصيد", "Balance")].map((label) => <th key={label} className="px-4 py-3 text-start">{label}</th>)}</tr></thead><tbody>{statement.entries.map((entry) => <tr key={entry.id} className="border-t border-slate-800 print:border-slate-200"><td className="px-4 py-3">{new Intl.DateTimeFormat(isArabic ? "ar-KW" : "en-GB").format(new Date(entry.date))}</td><td className="px-4 py-3">{entry.kind === "INVOICE" ? t("فاتورة", "Invoice") : t("دفعة", "Payment")}</td><td className="px-4 py-3" dir="ltr">{entry.reference}</td><td className="px-4 py-3">{entry.debit === "0.000" ? "—" : money(entry.debit)}</td><td className="px-4 py-3">{entry.credit === "0.000" ? "—" : money(entry.credit)}</td><td className="px-4 py-3 font-semibold">{money(entry.runningBalance)}</td></tr>)}{statement.entries.length === 0 ? <tr><td colSpan={6} className="px-4 py-10 text-center text-slate-500">{t("لا توجد حركات في هذه الفترة.", "No transactions in this period.")}</td></tr> : null}</tbody></table></div></> : null}
  </section>;
}
